SlackBuild tweaks, improved desc and required.

diff --git a/src/libraries/mpeg4ip/mpeg4ip.SlackBuild b/src/libraries/mpeg4ip/mpeg4ip.SlackBuild
--- a/src/libraries/mpeg4ip/mpeg4ip.SlackBuild
+++ b/src/libraries/mpeg4ip/mpeg4ip.SlackBuild
@@ -1,111 +1,180 @@
 #!/bin/sh
 
+##
+## Package Variables
+##
+
+PKGNAME=`basename $0 .SlackBuild`
 CWD=`pwd`
 TMP=${TMP:-/tmp}
-PKG=$TMP/package-mpeg4ip
+PKG=$TMP/package-$PKGNAME
+PKG_DEST=/home/packages
+VERSION=${VERSION:-1.6}
+ARCH=${ARCH:-i686}
+BUILD=${BUILD:-1}
+DISTRO=${DISTRO:-slackware}
 
-VERSION=1.5.0.1
-ARCH=${ARCH:-i486}
-BUILD=1
-
-if [ -f /var/log/packages/mpeg4ip-$VERSION-$ARCH-$BUILD ]; then
-  echo "mpeg4ip-$VERSION-$ARCH-$BUILD package already installed"
+## Installation Check
+if [ -f /var/log/packages/${PKGNAME}-${VERSION}-${ARCH}-${BUILD} ]; then
+  echo "${PKGNAME}-${VERSION}-${ARCH}-${BUILD} package already installed"
   exit 0
 fi
 
+##
+## Temporary Space
+##
 if [ ! -d $TMP ]; then
-  mkdir -p $TMP # location to build the source
+  mkdir -p $TMP 
 fi
 rm -rf $PKG
 mkdir -p $PKG
 
+##
+## Build Options
+##
+
 if [ "$ARCH" = "i386" ]; then
-  SLKCFLAGS="-O2 -march=i386 -mtune=i686"
+  GSB_CFLAGS="-O2 -march=i386 -mtune=i386"
   ARCH_CONFIGURE=""
 elif [ "$ARCH" = "i486" ]; then
-  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
+  GSB_CFLAGS="-O2 -march=i486 -mtune=i486"
+  ARCH_CONFIGURE=""
+elif [ "$ARCH" = "i686" ]; then
+  GSB_CFLAGS="-O3 -march=i686 -mtune=i686 -pipe -fomit-frame-pointer -ffast-math"
   ARCH_CONFIGURE=""
 elif [ "$ARCH" = "powerpc" ]; then
-  SLKCFLAGS="-O2"
-  ARCH_CONFIGURE=""
-elif [ "$ARCH" = "s390" ]; then
-  SLKCFLAGS="-O2"
+  GSB_CFLAGS="-O2"
   ARCH_CONFIGURE=""
 elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-O2 -fPIC"
+  GSB_CFLAGS="-O3 -fPIC -pipe -fomit-frame-pointer -ffast-math"
   ARCH_CONFIGURE="--libdir=/usr/lib64"
 fi
 
-cd $TMP
-tar -xzvf $CWD/mpeg4ip-$VERSION.tar.gz
-cd mpeg4ip-$VERSION
+## Decompress archive
+cd $TMP 
+tar xzf $CWD/${PKGNAME}-${VERSION}.tar.gz
+cd $PKGNAME-$VERSION
 
 # Apply $ARCH specific patches
 if [ "$ARCH" = "i386" ]; then
   echo "Applying patches for $ARCH"
-  #cat $CWD/foo.patch | patch -p0 --verbose
+  #cat $CWD/patches/foo.patch | patch -p0 --verbose
 elif [ "$ARCH" = "i486" ]; then
   echo "Applying patches for $ARCH"
-  #cat $CWD/foo.patch | patch -p0 --verbose
+  #cat $CWD/patches/foo.patch | patch -p0 --verbose
+elif [ "$ARCH" = "i686" ]; then
+  echo "Applying patches for $ARCH"
+  #cat $CWD/patches/foo.patch | patch -p0 --verbose
 elif [ "$ARCH" = "s390" ]; then
   echo "Applying patches for $ARCH"
-  #cat $CWD/foo.patch | patch -p0 --verbose
+  #cat $CWD/patches/foo.patch | patch -p0 --verbose
 elif [ "$ARCH" = "powerpc" ]; then
   echo "Applying patches for $ARCH"
-  #cat $CWD/foo.patch | patch -p0 --verbose
+  #cat $CWD/patches/foo.patch | patch -p0 --verbose
 elif [ "$ARCH" = "x86_64" ]; then
   echo "Applying patches for $ARCH"
-  #cat $CWD/foo.patch | patch -p0 --verbose
+  #cat $CWD/patches/foo.patch | patch -p0 --verbose
 fi
 
-./bootstrap
-CFLAGS="$SLKCFLAGS" \
-./configure --prefix=/usr \
-	    --program-prefix="" \
-	    --program-suffix="" \
-	    --disable-mp4live \
+##
+## Fix permissions for building
+##
+chown -R root.root .
+find . -perm 664 -exec chmod 644 {} \;
+find . -perm 600 -exec chmod 644 {} \;
+find . -perm 444 -exec chmod 644 {} \;
+find . -perm 400 -exec chmod 644 {} \;
+find . -perm 440 -exec chmod 644 {} \;
+find . -perm 777 -exec chmod 755 {} \;
+find . -perm 775 -exec chmod 755 {} \;
+find . -perm 511 -exec chmod 755 {} \;
+find . -perm 711 -exec chmod 755 {} \;
+find . -perm 555 -exec chmod 755 {} \;
+
+
+##
+## Run Configure and Build
+##
+## Add any local configuration options here.
+
+CFLAGS="$GSB_CFLAGS" \
+CXXFLAGS="$GSB_CFLAGS" \
+./boostrap --prefix=/usr \
             $ARCH_CONFIGURE \
-            $ARCH-slackware-linux || exit 1
-make || exit 1
+	    --sysconfdir=/etc \
+            --localstatedir=/var/lib \
+            --disable-static --enable-shared \
+            --disable-server \
+            --target=$ARCH-$DISTRO-linux || exit 1
+
+make -j4 || exit 1
 make install DESTDIR=$PKG
 
-(
-  cd $PKG/usr/include
-  cp mpeg4ip.h mpeg4ip.h.orig
-  grep -v '\(PACKAGE\)\|\(VERSION\)' mpeg4ip.h.orig > mpeg4ip.h
-  cp mpeg4ip_config.h mpeg4ip_config.h.orig
-  grep -v '\(PACKAGE\)\|\(VERSION\)' mpeg4ip_config.h.orig > mpeg4ip_config.h
-  rm mpeg4ip.h.orig mpeg4ip_config.h.orig
-)
+## Install Extra Documentation
+mkdir -p $PKG/usr/doc/$PKGNAME-$VERSION
+cp -a \
+  AUTHORS COPYING* ChangeLog NEWS README \
+  $PKG/usr/doc/$PKGNAME-$VERSION
+find $PKG/usr/doc/$PKGNAME-$VERSION/ -type f -exec chmod 644 {} \;
 
+##
+##  Permissions
+##
 chown -R $(stat --format "%u:%g" /usr/sbin) $PKG/usr/bin
+chown -R root.root $PKG/usr/doc/$PKGNAME-$VERSION/*
 
-mkdir -p $PKG/usr/doc/mpeg4ip-$VERSION
-cp -a AUTHORS COPYING ChangeLog INSTALL NEWS README \
-        TODO \
-        $PKG/usr/doc/mpeg4ip-$VERSION
-find $PKG/usr/doc/mpeg4ip-$VERSION/ -type f -exec chmod 644 {} \;
-chown root.root $PKG/usr/doc/mpeg4ip-$VERSION/*
-
-# strip:
+##
+## Strip Debugging Info
+##
 ( cd $PKG
   find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
   find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
 )
 
-gzip -9 $PKG/usr/man/*/*
-gzip -9 $PKG/usr/info/*
+##
+## Compress and Link Manpages
+##
+if [ -d $PKG/usr/man ]; then
+  ( cd $PKG/usr/man
+    for manpagedir in $(find . -type d -name "man*") ; do
+      ( cd $manpagedir
+        for eachpage in $( find . -type l -maxdepth 1) ; do
+          ln -s $( readlink $eachpage ).gz $eachpage.gz
+          rm $eachpage
+        done
+        gzip -9 *.?
+      )
+    done
+  )
+fi
 
+##
+## Slackware Package Information
+##
 mkdir -p $PKG/install
-cat $CWD/slack-required > $PKG/install/slack-required
-cat $CWD/slack-desc > $PKG/install/slack-desc
-cat $CWD/doinst.sh > $PKG/install/doinst.sh
+if [ -e $CWD/slack-required ]; then
+        cat $CWD/slack-required > $PKG/install/slack-required
+fi;
 
+if [ -e $CWD/slack-desc ]; then
+        cat $CWD/slack-desc > $PKG/install/slack-desc
+fi;
+
+if [ -e $CWD/doinst.sh ]; then
+        cat $CWD/doinst.sh > $PKG/install/doinst.sh
+fi;
+
+
+##
+## Make Slackware Package
+##
 cd $PKG
-makepkg -l y -c n $TMP/mpeg4ip-$VERSION-$ARCH-$BUILD.tgz
+makepkg -l y -c n $PKG_DEST/$PKGNAME-$VERSION-$ARCH-$BUILD.tgz
 
-# Clean up the extra stuff:
+##
+## Cleanup If Wanted
+##
 if [ "$1" = "--cleanup" ]; then
-  rm -rf $TMP/mpeg4ip-$VERSION
+  rm -rf $TMP/$PKGNAME-$VERSION
   rm -rf $PKG
 fi
