Schema cleanup.  Fix doinst.sh for rarian.

diff --git a/src/applications/gnome-screensaver/gnome-screensaver.SlackBuild b/src/applications/gnome-screensaver/gnome-screensaver.SlackBuild
--- a/src/applications/gnome-screensaver/gnome-screensaver.SlackBuild
+++ b/src/applications/gnome-screensaver/gnome-screensaver.SlackBuild
@@ -44,134 +44,129 @@ Options:  -force        The package will not be built if a package of the same
 EOF
 }
 
-    ## Parse command line arguments.
-    while [ $# -gt 0 ]; do
-    if [ "$1" = "-force" ]; then
-        FORCEBUILD=1
-        shift
-    elif [ "$1" = "-no-cleanup" ]; then
-        NOCLEANUP=1
-        shift
-    elif [ "$1" = "-help" ]; then
-        usage
-        exit 0
-    else
-        echo "${0##*/}: Unknown option: $1"
-        exit 1
-    fi
-    done
+## Parse command line arguments.
+while [ $# -gt 0 ]; do
+  if [ "$1" = "-force" ]; then
+    FORCEBUILD=1
+    shift
+  elif [ "$1" = "-no-cleanup" ]; then
+    NOCLEANUP=1
+    shift
+  elif [ "$1" = "-help" ]; then
+    usage
+    exit 0
+  else
+    echo "${0##*/}: Unknown option: $1"
+    exit 1
+  fi
+done
 
-    ## Package requirements and installation checks.
-    [ "$FORCEBUILD" = "0" ] && {
-    function check_installed() {
-        ls -1 /var/log/packages | grep "^${1}-[^-]*-[^-]*-[^-]*$" >/dev/null 2>&1
-        return $?
+## Package requirements and installation checks.
+[ "$FORCEBUILD" = "0" ] && {
+  function check_installed() {
+    ls -1 /var/log/packages | grep "^${1}-[^-]*-[^-]*-[^-]*$" >/dev/null 2>&1
+    return $?
+  }
+
+  check_installed "$PKGNAME" && {
+    echo "${0##*/}: Remove installed '$PKGNAME' package before build."
+    exit 1
+  }
+
+  for REQ in $REQUIRED_PACKAGES; do
+    check_installed "$REQ" || {
+      echo "${0##*/}: Required package '$REQ' not installed."
+      exit 1
     }
+  done
+}
 
-    check_installed "$PKGNAME" && {
-        echo "${0##*/}: Remove installed '$PKGNAME' package before build."
-        exit 1
-    }
+## Temporary space and package storage.
+mkdir -p $TMP
+rm -rf $PKG
+mkdir -p $PKG
+mkdir -p $PKG/install
+mkdir -p $PKGDEST
 
-    for REQ in $REQUIRED_PACKAGES; do
-        check_installed "$REQ" || {
-        echo "${0##*/}: Required package '$REQ' not installed."
-        exit 1
-        }
-    done
-    }
+## Decompress archive.
+cd $TMP &&
+tar xjf $CWD/$PKGNAME-$VERSION.tar.bz2 &&
+cd $PKGNAME-$VERSION || exit 1
 
-    ## Temporary space and package storage.
-    mkdir -p $TMP
-    rm -rf $PKG
-    mkdir -p $PKG
-    mkdir -p $PKG/install
-    mkdir -p $PKGDEST
+# Apply ARCH specific patches.
+if [ "$ARCH" = "i386" ]; then
+  echo "${0##*/}: Applying any patches for $ARCH"
+  #cat $CWD/patches/foo.patch | patch -p0 --verbose
+elif [ "$ARCH" = "i486" ]; then
+  echo "${0##*/}: Applying any patches for $ARCH"
+  #cat $CWD/patches/foo.patch | patch -p0 --verbose
+elif [ "$ARCH" = "i586" ]; then
+  echo "${0##*/}: Applying any patches for $ARCH"
+  #cat $CWD/patches/foo.patch | patch -p0 --verbose
+elif [ "$ARCH" = "i686" ]; then
+  echo "${0##*/}: Applying any patches for $ARCH"
+  #cat $CWD/patches/foo.patch | patch -p0 --verbose
+elif [ "$ARCH" = "x86_64" ]; then
+  echo "${0##*/}: Applying any patches for $ARCH"
+  #cat $CWD/patches/foo.patch | patch -p0 --verbose
+elif [ "$ARCH" = "powerpc" ]; then
+  echo "${0##*/}: Applying any patches for $ARCH"
+  #cat $CWD/patches/foo.patch | patch -p0 --verbose
+fi
 
-    ## Decompress archive.
-    cd $TMP &&
-    tar xjf $CWD/$PKGNAME-$VERSION.tar.bz2 &&
-    cd $PKGNAME-$VERSION || exit 1
+## Fix permissions for building.
+chown -R root.root .
+find . -perm 664 -exec chmod 644 {} \;
+find . -perm 600 -exec chmod 644 {} \;
+find . -perm 444 -exec chmod 644 {} \;
+find . -perm 400 -exec chmod 644 {} \;
+find . -perm 440 -exec chmod 644 {} \;
+find . -perm 777 -exec chmod 755 {} \;
+find . -perm 775 -exec chmod 755 {} \;
+find . -perm 511 -exec chmod 755 {} \;
+find . -perm 711 -exec chmod 755 {} \;
+find . -perm 555 -exec chmod 755 {} \;
 
-    # Apply ARCH specific patches.
-    if [ "$ARCH" = "i386" ]; then
-    echo "${0##*/}: Applying any patches for $ARCH"
-    #cat $CWD/patches/foo.patch | patch -p0 --verbose
-    elif [ "$ARCH" = "i486" ]; then
-    echo "${0##*/}: Applying any patches for $ARCH"
-    #cat $CWD/patches/foo.patch | patch -p0 --verbose
-    elif [ "$ARCH" = "i586" ]; then
-    echo "${0##*/}: Applying any patches for $ARCH"
-    #cat $CWD/patches/foo.patch | patch -p0 --verbose
-    elif [ "$ARCH" = "i686" ]; then
-    echo "${0##*/}: Applying any patches for $ARCH"
-    #cat $CWD/patches/foo.patch | patch -p0 --verbose
-    elif [ "$ARCH" = "x86_64" ]; then
-    echo "${0##*/}: Applying any patches for $ARCH"
-    #cat $CWD/patches/foo.patch | patch -p0 --verbose
-    elif [ "$ARCH" = "powerpc" ]; then
-    echo "${0##*/}: Applying any patches for $ARCH"
-    #cat $CWD/patches/foo.patch | patch -p0 --verbose
-    fi
+## Configure, Tuning, GCC and Make options.
+CONFIGURE_FLAGS=${GSB_CONFIGURE_FLAGS:-""}
+if [ "$ARCH" = "i386" ]; then
+  TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2 -march=$ARCH -mtune=$TUNE"}
+elif [ "$ARCH" = "i486" ]; then
+  TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2 -march=$ARCH -mtune=$TUNE"}
+elif [ "$ARCH" = "i586" ]; then
+  TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O3 -march=$ARCH -mtune=$TUNE -pipe -fomit-frame-pointer -ffast-math"}
+elif [ "$ARCH" = "i686" ]; then
+  TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O3 -march=$ARCH -mtune=$TUNE -pipe -fomit-frame-pointer -ffast-math"}
+elif [ "$ARCH" = "x86_64" ]; then
+  if [ "$TUNE" = "k8" -o "$TUNE" = "opteron" -o "$TUNE" = "athlon64" -o "$TUNE" = "athlon-fx" ]; then
+    TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O3 -march=$TUNE -mtune=$TUNE -pipe -fomit-frame-pointer -ffast-math -fPIC"}
+  else
+    TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O3 -march=k8 -mtune=k8 -pipe -fomit-frame-pointer -ffast-math -fPIC"}
+  fi
+  [ -z "$CONFIGURE_FLAGS" ] && {
+    CONFIGURE_FLAGS="--libdir=/usr/lib64"
+  }
+elif [ "$ARCH" = "powerpc" ]; then
+  TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2 -march=$ARCH"}
+else
+  TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2"}
+fi
+EXTRA_CFLAGS=${GSB_EXTRA_CFLAGS:-""}
+MAKE_FLAGS=${GSB_MAKE_FLAGS:-""}
 
-    ## Fix permissions for building.
-    chown -R root.root .
-    find . -perm 664 -exec chmod 644 {} \;
-    find . -perm 600 -exec chmod 644 {} \;
-    find . -perm 444 -exec chmod 644 {} \;
-    find . -perm 400 -exec chmod 644 {} \;
-    find . -perm 440 -exec chmod 644 {} \;
-    find . -perm 777 -exec chmod 755 {} \;
-    find . -perm 775 -exec chmod 755 {} \;
-    find . -perm 511 -exec chmod 755 {} \;
-    find . -perm 711 -exec chmod 755 {} \;
-    find . -perm 555 -exec chmod 755 {} \;
-
-    ## Configure, Tuning, GCC and Make options.
-    CONFIGURE_FLAGS=${GSB_CONFIGURE_FLAGS:-""}
-    if [ "$ARCH" = "i386" ]; then
-    TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2 -march=$ARCH -mtune=$TUNE"}
-    elif [ "$ARCH" = "i486" ]; then
-    TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2 -march=$ARCH -mtune=$TUNE"}
-    elif [ "$ARCH" = "i586" ]; then
-    TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O3 -march=$ARCH -mtune=$TUNE -pipe -fomit-frame-pointer -ffast-math"}
-    elif [ "$ARCH" = "i686" ]; then
-    TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O3 -march=$ARCH -mtune=$TUNE -pipe -fomit-frame-pointer -ffast-math"}
-    elif [ "$ARCH" = "x86_64" ]; then
-    if [ "$TUNE" = "k8" -o "$TUNE" = "opteron" -o "$TUNE" = "athlon64" -o "$TUNE" = "athlon-fx" ]; then
-        TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O3 -march=$TUNE -mtune=$TUNE -pipe -fomit-frame-pointer -ffast-math -fPIC"}
-    else
-        TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O3 -march=k8 -mtune=k8 -pipe -fomit-frame-pointer -ffast-math -fPIC"}
-    fi
-    [ -z "$CONFIGURE_FLAGS" ] && {
-        CONFIGURE_FLAGS="--libdir=/usr/lib64"
-    }
-    elif [ "$ARCH" = "powerpc" ]; then
-    TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2 -march=$ARCH"}
-    else
-    TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2"}
-    fi
-    EXTRA_CFLAGS=${GSB_EXTRA_CFLAGS:-""}
-    MAKE_FLAGS=${GSB_MAKE_FLAGS:-""}
-
-    ## Configure.
-    ## The default is to build shared libraries, no static libraries, install into
-    ## /usr and use /etc as the config directory.
-    ## For packages with GNOME Schemas, additional options are required:
-    ##  --disable-schemas-install --with-gconf-schema-file-dir=/etc/gconf/schemas \
-    ##  --with-gconf-source=`/usr/bin/gconftool-2 --get-default-source` \
-    CFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" CXXFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" \
-    ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var/lib \
-    $CONFIGURE_FLAGS --target=$ARCH-$DISTRO-linux \
-    --disable-static --enable-shared \
-    --disable-pam  \
-    --with-shadow \
-    --with-libgl \
-    --with-xscreensaverhackdir=/usr/libexec/xscreensaver \
-    --with-xscreensaverdir=/usr/share/xscreensaver \
-    --disable-schemas-install --with-gconf-schema-file-dir=/etc/gconf/schemas \
-    --with-gconf-source=`/usr/bin/gconftool-2 --get-default-source` \
-    || exit 1
+## Configure.
+CFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" CXXFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" \
+  ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var/lib \
+  $CONFIGURE_FLAGS --target=$ARCH-$DISTRO-linux \
+  --disable-static --enable-shared \
+  --disable-pam  \
+  --with-shadow \
+  --with-libgl \
+  --with-xscreensaverhackdir=/usr/libexec/xscreensaver \
+  --with-xscreensaverdir=/usr/share/xscreensaver \
+  --disable-schemas-install --with-gconf-schema-file-dir=/etc/gconf/schemas \
+  --with-gconf-source=`/usr/bin/gconftool-2 --get-default-source` \
+  || exit 1
 
 ## Build and install.
 make $MAKE_FLAGS &&
@@ -186,14 +181,14 @@ chmod +x $PKG/usr/libexec/gnome-screensaver/migrate-xscreensaver-config.sh
 
 ## Strip debugging symbols.
 { find $PKG | xargs file | egrep "executable|shared object" | grep "ELF" | \
-cut -d: -f1 | xargs strip --strip-unneeded ; } 2>/dev/null
+  cut -d: -f1 | xargs strip --strip-unneeded ; } 2>/dev/null
 
 ## Compress and fix manpage links.
 [ -e $PKG/usr/man ] && {
-find $PKG/usr/man -type f -name \*.? -exec gzip -9f {} \;
-find $PKG/usr/man -type l -name \*.? -printf \
+  find $PKG/usr/man -type f -name \*.? -exec gzip -9f {} \;
+  find $PKG/usr/man -type l -name \*.? -printf \
     "( cd '%h'; [ -e '%l.gz' ] &&
-    { rm -f '%f'; ln -sf '%l.gz' '%f.gz'; } );\n" | bash
+     { rm -f '%f'; ln -sf '%l.gz' '%f.gz'; } );\n" | bash
 }
 
 ## Deal with .info files.
@@ -217,10 +212,10 @@ chown -R root:root $PKG/usr/doc/$PKGNAME-$VERSION
     for FILE in *; do
       [ -z "$(grep gconfentry $FILE)" ] && {
         # Create gconf tree
-        echo "GCONF_CONFIG_SOURCE=\"\$(usr/bin/gconftool-2 --get-default-source)\" usr/bin/gconftool -2 --makefile-install-rule etc/gconf/schemas/$FILE >/dev/null 2>&1" >>$PKG/install/doinst.sh
+        echo "GCONF_CONFIG_SOURCE=\"\$(usr/bin/gconftool-2 --get-default-source)\" usr/bin/gconftool-2 --makefile-install-rule etc/gconf/schemas/$FILE >/dev/null 2>&1" >>$PKG/install/doinst.sh
       } || {
         # Load gconf settings
-        echo "GCONF_CONFIG_SOURCE=\"\$(usr/bin/gconftool-2 --get-default-source)\" usr/bin/gconftool -2 --config-source=\$(usr/bin/gconftool-2 --get-default-source) --direct --load etc/gconf/schemas/$FILE >/dev/null 2>&1" >>$PKG/install/doinst.sh
+        echo "GCONF_CONFIG_SOURCE=\"\$(usr/bin/gconftool-2 --get-default-source)\" usr/bin/gconftool-2 --config-source=\$(usr/bin/gconftool-2 --get-default-source) --direct --load etc/gconf/schemas/$FILE >/dev/null 2>&1" >>$PKG/install/doinst.sh
       }
     done
   )
