* update ck download link * add gksu to gdm * upgrade gdl, and NM to latest stable

diff --git a/src/n/NetworkManager/NetworkManager.SlackBuild b/src/n/NetworkManager/NetworkManager.SlackBuild
--- a/src/n/NetworkManager/NetworkManager.SlackBuild
+++ b/src/n/NetworkManager/NetworkManager.SlackBuild
@@ -24,8 +24,8 @@
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 # Package variables.
-BUILD=3
-VERSION=0.7.1
+BUILD=1
+VERSION=0.7.2
 
 # List any packages here that are required to build this package.
 # The list is space seperated and case sensitive.
@@ -152,40 +152,49 @@ fi
 EXTRA_CFLAGS=${GSB_EXTRA_CFLAGS:-""}
 MAKE_FLAGS=${GSB_MAKE_FLAGS:-""}
 
-# NetworkManager requires dhcpcd4 in order to function properly; rather than
-# include another dhcpcd package, we'll put our NM dhcpcd4 privately in libexec
+# NetworkManager requires dhcpcd5 in order to function properly; rather than
+# include another dhcpcd package, we'll put our NM dhcpcd5 privately in libexec
 # since on a Slackware system, pretty much only NM will use it.  
-# Grab our internal dhcpcd4
-mkdir dhcpcd4 &&
-cd dhcpcd4 &&
-if [ ! -f dhcpcd-4.0.13.tar.bz2 ]; then
-	wget -c http://roy.marples.name/downloads/dhcpcd/dhcpcd-4.0.13.tar.bz2 || exit 1
-fi;
-tar xfj dhcpcd-4.0.13.tar.bz2 &&
-cd dhcpcd-4.0.13 &&
-make ${MAKE_FLAGS} SYSCONFDIR=/usr/libexec/dhcpcd4 \
-BINDIR=/usr/libexec/dhcpcd4 \
-LIBEXECDIR=/usr/libexec/dhcpcd4 \
-DESTDIR=$PKG install || exit 1
-rm -fr $PKG/usr/share 
-# Done dhcpcd4 build
+# Grab our internal dhcpcd5
+
+# DHCP5 Download information
+DHCP_HOMEPAGE="http://roy.marples.name/projects/dhcpcd/wiki"
+DHCP_VERSION="5.1.3"
+DHCP_DOWNLOAD="http://roy.marples.name/downloads/dhcpcd/dhcpcd-5.1.3.tar.bz2"
+DHCP_MD5SUM="f852090ad221b6331478f50fc1aa539e"
+mkdir dhcpcd5 &&
+cd dhcpcd5 &&
+rm -fr dhcpcd* &&
+wget -c $DHCP_DOWNLOAD || exit 1
+[ "$(md5sum dhcpcd-${DHCP_VERSION}.tar.bz2 | cut -f1 -d\ )" = "${DHCP_MD5SUM}" ] || {
+ echo "dhcpcd package has an invalid md5sum."
+ exit 1
+}
+tar xfj dhcpcd-$DHCP_VERSION.tar.bz2 &&
+cd dhcpcd-$DHCP_VERSION &&
+./configure --prefix=/usr/libexec/dhcpcd5 --libexecdir=/usr/libexec/dhcpcd5 \
+  --dbdir=/var/lib/dhcpcd --sysconfdir=/usr/libexec/dhcpcd5 &&
+make ${MAKE_FLAGS} &&
+make DESTDIR=$PKG install || exit 1
+rm -fr $PKG/usr/libexec/dhcpcd5/share &&
+mv $PKG/usr/libexec/dhcpcd5/sbin/dhcpcd $PKG/usr/libexec/dhcpcd5 &&
+rm -fr $PKG/usr/libexec/dhcpcd/share &&
+rm -fr $PKG/usr/libexec/dhcpcd/sbin || exit 1
+# Done dhcpcd5 build
 # Restore proper CWD
 cd $TMP/$PKGNAME-$VERSION 
 
 # NetworkManager Configure.
 CFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" CXXFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" \
-  ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var/lib \
-  $CONFIGURE_FLAGS \
+  ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var \
   --libdir=/usr/lib${LIBDIRSUFFIX} \
   --build=$ARCH-$DISTRO-linux \
   --target=$ARCH-$DISTRO-linux \
   --mandir=/usr/man \
-  --disable-static --enable-shared \
+  --disable-static \
+  --enable-shared \
   --with-distro=slackware \
-  --with-mdns-provider=avahi \
-  --with-dbus-sys=/etc/dbus-1/system.d \
-  --enable-notification-icon \
-  --with-dhcp-client=/usr/libexec/dhcpcd4/dhcpcd \
+  --with-dhcp-client=/usr/libexec/dhcpcd5/dhcpcd \
   --with-crypto=nss \
   --with-docs \
   || exit 1
