Add improved menu-kde-cleanup patch by Arislzo. Bump build.

diff --git a/src/desktop/gnome-menus/gnome-menus.SlackBuild b/src/desktop/gnome-menus/gnome-menus.SlackBuild
--- a/src/desktop/gnome-menus/gnome-menus.SlackBuild
+++ b/src/desktop/gnome-menus/gnome-menus.SlackBuild
@@ -7,7 +7,7 @@
 ##
 
 ## Package variables.
-BUILD=5
+BUILD=6
 VERSION=2.20.3
 
 ## List any packages here that are required to build this package.
@@ -114,14 +114,17 @@ elif [ "$ARCH" = "powerpc" ]; then
   #cat $CWD/patches/foo.patch | patch -p0 --verbose
 fi
 
-# Patch to clean up menus by removing KDE and Xfce items
+# Patch to clean up menus by removing KDE 
 # This patch addes "Exclude" sections to the applications.menu
 # to avoid KDE items in the GNOME menu
-patch -p0 < $CWD/patches/gnome-menus-2.20.3-menu-cleanup.patch || exit 1
+# gnome-menus-2.20.3-menu-cleanup.patch deprecated by exclude-kde patch
+#patch -p0 < $CWD/patches/gnome-menus-2.20.3-menu-cleanup.patch || exit 1
+patch -p0 < $CWD/patches/gnome-menus-2.20.3-exclude-kde.patch || exit 1
 
 # Patch to prefix gnome xfg menus with "gnome-" in order
 # to keep seperate from KDE menus.
 #patch -p0 < $CWD/patches/gnome-menus-2.20.3-xdg-prefix.patch || exit 1
+
 
 ## Fix permissions for building.
 chown -R root.root .
