* whack of updates for platform/ section * update bluez * add .info files a la slackbuilds.org, handy for users * remove some older packages * note: under heavy construction, for testing not for building :)

diff --git a/src/platform/avahi/avahi.SlackBuild b/src/platform/avahi/avahi.SlackBuild
--- a/src/platform/avahi/avahi.SlackBuild
+++ b/src/platform/avahi/avahi.SlackBuild
@@ -1,35 +1,53 @@
 #!/bin/bash
-## Version: 1.6 GSB Package SlackBuild.
-## Copyright (c) 2007 Darren 'Tadgy' Austin <darren (at) gnomeslackbuild.org>
-## Copyright (c) 2007 Steve Kennedy <sk238 (at) exeter.ac.uk>
-##
-## Licenced under the terms of the GNU General Public Licence version 3.
-##
+# Version: 1.7 GSB Package SlackBuild.
+# Copyright (c) 2007,2008,2009 Darren 'Tadgy' Austin <darren (at) gnomeslackbuild.org>
+# Copyright (c) 2007,2008,2009 Steve Kennedy <steve (at) gnomeslackbuild.org>
+# All rights reserved.
+#
+# Licenced under the terms of the GNU General Public Licence version 3.
+#
+# Redistribution and use of this script, with or without modification, is
+# permitted provided that the following conditions are met:
+#
+# 1. Redistributions of this script must retain the above copyright
+#    notice, this list of conditions and the following disclaimer.
+#
+#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
+#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
+#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
+#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
+#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
+#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
+#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
+#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
+#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
+#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-## Package variables
-BUILD=6
+# Package variables
+BUILD=7
 VERSION=0.6.25
 
-## List any packages here that are required to build this package.
-## The list is space seperated and case sensitive.
+# List any packages here that are required to build this package.
+# The list is space seperated and case sensitive.
+REQUIRED_PACKAGES="glib2 desktop-file-utils dbus gtk+2 python pygtk dbus-python expat \
+                   libglade pygobject gdbm"
 
-REQUIRED_PACKAGES="glib2 desktop-file-utils dbus gtk+2 python pygtk dbus-python expat libdaemon libglade pygobject gdbm"
-
-## Build variables.
-ARCH=${ARCH:-i586}
-TUNE=${TUNE:-i586}
+# Build variables.
+TAG=${TAG:-gsb}
+ARCH=${ARCH:-i486}
+TUNE=${TUNE:-i486}
 DISTRO=${DISTRO:-slackware}
 TMP=${TMP:-/tmp}
 PKGDEST=${PKGDEST:-$TMP}
 
-## Script variables.
+# Script variables.
 PKGNAME=$(basename $0 .SlackBuild)
 PKG=$TMP/package-$PKGNAME
 CWD=$(pwd)
 NOCLEANUP=0
 FORCEBUILD=0
 
-## Usage.
+# Usage.
 function usage() {
   cat << EOF
 Usage: ${0##*/} [options]
@@ -45,7 +63,7 @@ Options:  --force       The package will not be built if a package of the same
 EOF
 }
 
-## Parse command line arguments.
+# Parse command line arguments.
 while [ $# -gt 0 ]; do
   if [ "$1" = "-force" ] || [ "$1" = "--force" ]; then
     FORCEBUILD=1
@@ -62,7 +80,7 @@ while [ $# -gt 0 ]; do
   fi
 done
 
-## Package requirements and installation checks.
+# Package requirements and installation checks.
 [ "$FORCEBUILD" = "0" ] && {
   function check_installed() {
     ls -1 /var/log/packages | grep "^${1}-[^-]*-[^-]*-[^-]*$" >/dev/null 2>&1
@@ -82,108 +100,75 @@ done
   done
 }
 
-## Temporary space and package storage.
+# Temporary space and package storage.
 mkdir -p $TMP
 rm -rf $PKG
 mkdir -p $PKG
 mkdir -p $PKG/install
 mkdir -p $PKGDEST
 
-## Decompress archive.
+# Decompress archive.
 cd $TMP &&
 tar xzf $CWD/$PKGNAME-$VERSION.tar.gz &&
 cd $PKGNAME-$VERSION || exit 1
 
 # Apply ARCH specific patches.
-if [ "$ARCH" = "i386" ]; then
-  echo "${0##*/}: Applying any patches for $ARCH"
-  #cat $CWD/patches/foo.patch | patch -p0 --verbose
-elif [ "$ARCH" = "i486" ]; then
-  echo "${0##*/}: Applying any patches for $ARCH"
-  #cat $CWD/patches/foo.patch | patch -p0 --verbose
-elif [ "$ARCH" = "i586" ]; then
-  echo "${0##*/}: Applying any patches for $ARCH"
-  #cat $CWD/patches/foo.patch | patch -p0 --verbose
-elif [ "$ARCH" = "i686" ]; then
+if [ "$ARCH" = "i486" -o "$ARCH" = "i586" -o "$ARCH" = "i686" ]; then
   echo "${0##*/}: Applying any patches for $ARCH"
   #cat $CWD/patches/foo.patch | patch -p0 --verbose
 elif [ "$ARCH" = "x86_64" ]; then
   echo "${0##*/}: Applying any patches for $ARCH"
-  #patch -p0 < $CWD/patches/pygtk-slamd64.patch
+  #cat $CWD/patches/foo.patch | patch -p0 --verbose
 elif [ "$ARCH" = "powerpc" ]; then
   echo "${0##*/}: Applying any patches for $ARCH"
   #cat $CWD/patches/foo.patch | patch -p0 --verbose
 fi
 
-## See patches/README
-if [ -x `which pkg-config` ]; then
-   pkg-config --atleast-version="1.1.1" dbus-1
-   if [ $? -ne 0 ]; then
-     echo "You do not have dbus greater or equal to 1.1.1. A patch is required."
-     (cd $TMP/$PKGNAME-$VERSION;
-      patch -p0 < $CWD/patches/avahi.dbus.patch
-     );
-   fi;
-else
-   echo "Need pkg-config in order to build this package.";
-   exit 1;
-fi;
+# Fix permissions for building.
+chown -R root:root .
+find . \
+  \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
+  -exec chmod 755 {} \; -o \
+  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
+  -exec chmod 644 {} \;
 
-## Fix permissions for building.
-chown -R root.root .
-find . -perm 664 -exec chmod 644 {} \;
-find . -perm 600 -exec chmod 644 {} \;
-find . -perm 444 -exec chmod 644 {} \;
-find . -perm 400 -exec chmod 644 {} \;
-find . -perm 440 -exec chmod 644 {} \;
-find . -perm 777 -exec chmod 755 {} \;
-find . -perm 775 -exec chmod 755 {} \;
-find . -perm 511 -exec chmod 755 {} \;
-find . -perm 711 -exec chmod 755 {} \;
-find . -perm 555 -exec chmod 755 {} \;
-
-## Configure, Tuning, GCC and Make options.
+# Configure, Tuning, GCC and Make options.
 CONFIGURE_FLAGS=${GSB_CONFIGURE_FLAGS:-""}
-if [ "$ARCH" = "i386" ]; then
+if [ "$ARCH" = "i486" -o "$ARCH" = "i586" ]; then
   TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2 -march=$ARCH -mtune=$TUNE"}
-elif [ "$ARCH" = "i486" ]; then
-  TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2 -march=$ARCH -mtune=$TUNE"}
-elif [ "$ARCH" = "i586" ]; then
-  TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O3 -march=$ARCH -mtune=$TUNE -pipe -fomit-frame-pointer"}
+  LIBDIRSUFFIX=""
 elif [ "$ARCH" = "i686" ]; then
-  TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O3 -march=$ARCH -mtune=$TUNE -pipe -fomit-frame-pointer"}
+  TUNE_CFLAGS="-O2 -march=i686 -mtune=i686"
+  LIBDIRSUFFIX=""
+elif [ "$ARCH" = "s390" ]; then
+  TUNE_CFLAGS="-O2"
+  LIBDIRSUFFIX=""
 elif [ "$ARCH" = "x86_64" ]; then
-  if [ "$TUNE" = "k8" -o "$TUNE" = "opteron" -o "$TUNE" = "athlon64" -o "$TUNE" = "athlon-fx" ]; then
-    TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O3 -march=$TUNE -mtune=$TUNE -pipe -fomit-frame-pointer -fPIC"}
-  else
-    TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O3 -march=k8 -mtune=k8 -pipe -fomit-frame-pointer -fPIC"}
-  fi
-  [ -z "$CONFIGURE_FLAGS" ] && {
-    CONFIGURE_FLAGS="--libdir=/usr/lib64"
-  }
+    TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2 -fPIC"}
+    LIBDIRSUFFIX="64"
 elif [ "$ARCH" = "powerpc" ]; then
   TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2 -march=$ARCH"}
-else
-  TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2"}
 fi
 EXTRA_CFLAGS=${GSB_EXTRA_CFLAGS:-""}
 MAKE_FLAGS=${GSB_MAKE_FLAGS:-""}
 
-## Quick check for user/groups
+# We need to make sure we have avahi added to /etc/passwd before configure
 if ! grep -q "^avahi:" /etc/passwd; then
-  echo "Make sure to add 'avahi' to /etc/passwd before running."
-  exit 1
+  /usr/sbin/useradd -u 85 -s /bin/false -d /dev/null avahi || exit 1
+  /usr/sbin/useradd -u 88 -s /bin/false -d /dev/null avahi-autoipd || exit 1
 fi 
+# We need to make sure we have avahi added to /etc/group before configure
 if ! grep -q "^avahi:" /etc/group; then
-  echo "Make sure to add 'avahi' to /etc/group before running."
-  exit 1
+  /usr/sbin/groupadd -g 85 avahi || exit 1
 fi 
 
-## Configure.
+# Configure.
 CFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" CXXFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" \
   ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var \
   --mandir=/usr/man $CONFIGURE_FLAGS --target=$ARCH-$DISTRO-linux \
-  --disable-static --enable-shared \
+  --libdir=/usr/lib${LIBDIRSUFFIX} \
+  --disable-static \
+  --enable-shared \
   --disable-monodoc \
   --disable-mono \
   --enable-python-dbus \
@@ -200,40 +185,40 @@ CFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" CXXFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" \
   --with-autoipd-user=avahi-autoipd \
   --with-autoipd-group=avahi-autoipd \
   --with-distro=slackware \
-  --enable-compat-howl \
-  --enable-compat-libdns_sd \
   --program-prefix= \
   --program-suffix= \
   || exit 1
 
-## Build and install.
+# Build and install.
 make $MAKE_FLAGS &&
 make $MAKE_FLAGS DESTDIR=$PKG install || exit 1
 
-## re-enable signals in dbus
-mkdir -p $PKG/etc/dbus-1 &&
-cp $CWD/system-local.conf $PKG/etc/dbus-1/system-local.conf.new || exit 1
-chmod 644 $PKG/etc/dbus-1/system-local.conf.new || exit 1
+# We need to re-enable signals in dbus for service browsing 
+#mkdir -p $PKG/etc/dbus-1 &&
+#cp $CWD/system-local.conf $PKG/etc/dbus-1/system-local.conf.new || exit 1
+#chmod 644 $PKG/etc/dbus-1/system-local.conf.new || exit 1
 
-## Setup up autoipd dirs
+# Setup up autoipd dirs
 mkdir -p ${PKG}/var/run/avahi-daemon
 mkdir -p ${PKG}/var/run/avahi-autoipd 
-## Remove extraneous icons
+
+# Remove extraneous icons from gnome menus
 rm -fr $PKG/usr/share/applications/bssh.desktop
 rm -fr $PKG/usr/share/applications/bvnc.desktop
 
-## Preserve previously installed configuations.
+# Preserve previously installed configuations.
 ( cd $PKG/etc/rc.d
   for i in avahidaemon avahidnsconfd
   do
     mv rc.$i rc.$i.new
   done)
+mv $PKG/etc/dbus-1/system.d/avahi-dbus.conf $PKG/etc/dbus-1/system.d/avahi-dbus.conf.new || exit 1
 
-## Strip debugging symbols.
+# Strip debugging symbols.
 { find $PKG | xargs file | egrep "executable|shared object" | grep "ELF" | \
   cut -d: -f1 | xargs strip --strip-unneeded ; } 2>/dev/null
 
-## Compress and fix manpage links.
+# Compress and fix manpage links.
 [ -e $PKG/usr/man ] && {
   find $PKG/usr/man -type f -name \*.? -exec gzip -9f {} \;
   find $PKG/usr/man -type l -name \*.? -printf \
@@ -241,20 +226,24 @@ rm -fr $PKG/usr/share/applications/bvnc.desktop
      { rm -f '%f'; ln -sf '%l.gz' '%f.gz'; } );\n" | bash
 }
 
-## Deal with .info files.
+# Deal with .info files.
+[ -e $PKG/usr/share/info ] && {
+  mkdir -p $PKG/usr && mv $PKG/usr/share/info $PKG/usr || exit 1;
+  rmdir -p $PKG/usr/share
+  }
 [ -e $PKG/usr/info ] && {
   rm -f $PKG/usr/info/dir
   gzip -9 $PKG/usr/info/*.info
 }
 
-## Copy extra documentation into package.
+# Copy extra documentation into package.
 mkdir -p $PKG/usr/doc/$PKGNAME-$VERSION
-cp -a LICENSE docs/* \
+cp -a LICENSE docs/README docs/AUTHORS docs/NEWS docs/*.dia \
   $PKG/usr/doc/$PKGNAME-$VERSION
 find $PKG/usr/doc/$PKGNAME-$VERSION/ -type f -exec chmod 644 {} \;
 chown -R root:root $PKG/usr/doc/$PKGNAME-$VERSION
 
-## Package meta files
+# Package meta files
 for FILE in doinst.sh slack-desc slack-required slack-conflicts slack-suggests
 do
   [ -e $CWD/$FILE ] && {
@@ -262,11 +251,11 @@ do
   }
 done
 
-## Create the package
+# Create the package
 cd $PKG
-makepkg -p -l y -c n $PKGDEST/$PKGNAME-${VERSION//-/_}-$ARCH-$BUILD.tgz
+makepkg -p -l y -c n $PKGDEST/$PKGNAME-${VERSION//-/_}-$ARCH-${BUILD}${TAG}.txz
 
-## Cleanup
+# Cleanup
 [ "$NOCLEANUP" = "0" ] && {
   rm -rf $PKG $TMP/$PKGNAME-$VERSION
 }
diff --git a/src/platform/bluez/bluez.SlackBuild b/src/platform/bluez/bluez.SlackBuild
--- a/src/platform/bluez/bluez.SlackBuild
+++ b/src/platform/bluez/bluez.SlackBuild
@@ -1,37 +1,52 @@
 #!/bin/bash
-## Version: 1.6 GSB Package SlackBuild - Do not remove this line!
-## Copyright (c) 2007, 2008:
-##   Darren 'Tadgy' Austin <darren (at) gnomeslackbuild.org>, Coventry, UK.
-##   Steve Kennedy <steve (at) gnomeslackbuild.org>, Exeter, UK.
-## Licenced under the terms of the GNU General Public Licence version 3.
-##
-## Some portions are Copyright 2006, 2008  Patrick J. Volkerding, Sebeka, MN, USA
-## All rights reserved.
+# Version: 1.7 GSB Package SlackBuild.
+# Copyright (c) 2007,2008,2009 Darren 'Tadgy' Austin <darren (at) gnomeslackbuild.org>
+# Copyright (c) 2007,2008,2009 Steve Kennedy <steve (at) gnomeslackbuild.org>
+# All rights reserved.
+#
+# Licenced under the terms of the GNU General Public Licence version 3.
+#
+# Redistribution and use of this script, with or without modification, is
+# permitted provided that the following conditions are met:
+#
+# 1. Redistributions of this script must retain the above copyright
+#    notice, this list of conditions and the following disclaimer.
+#
+#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
+#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
+#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
+#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
+#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
+#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
+#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
+#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
+#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
+#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
+# Package variables.
+BUILD=1
+VERSION=4.40
 
-## Package variables.
-BUILD=7
-VERSION=4.37
-
-## List any packages here that are required to build this package.
-## The list is space seperated and case sensitive.
+# List any packages here that are required to build this package.
+# The list is space seperated and case sensitive.
 REQUIRED_PACKAGES="alsa-lib dbus glib2 gstreamer gst-plugins-base libsndfile cups"
 
-## Build variables.
+# Build variables.
+TAG=${TAG:-gsb}
 ARCH=${ARCH:-i586}
 TUNE=${TUNE:-i586}
 DISTRO=${DISTRO:-slackware}
 TMP=${TMP:-/tmp}
 PKGDEST=${PKGDEST:-$TMP}
 
-## Script variables.
+# Script variables.
 PKGNAME=$(basename $0 .SlackBuild)
 PKG=$TMP/package-$PKGNAME
 CWD=$(pwd)
 NOCLEANUP=0
 FORCEBUILD=0
 
-## Usage.
+# Usage.
 function usage() {
   cat << EOF
 Usage: ${0##*/} [options]
@@ -47,7 +62,7 @@ Options:  --force       The package will not be built if a package of the same
 EOF
 }
 
-## Parse command line arguments.
+# Parse command line arguments.
 while [ $# -gt 0 ]; do
   if [ "$1" = "-force" ] || [ "$1" = "--force" ]; then
     FORCEBUILD=1
@@ -64,7 +79,7 @@ while [ $# -gt 0 ]; do
   fi
 done
 
-## Package requirements and installation checks.
+# Package requirements and installation checks.
 [ "$FORCEBUILD" = "0" ] && {
   function check_installed() {
     ls -1 /var/log/packages | grep "^${1}-[^-]*-[^-]*-[^-]*$" >/dev/null 2>&1
@@ -94,30 +109,21 @@ done
   done
 }
 
-## Temporary space and package storage.
+# Temporary space and package storage.
 mkdir -p $TMP
 rm -rf $PKG
 mkdir -p $PKG
 mkdir -p $PKG/install
 mkdir -p $PKGDEST
 
-## Decompress archive.
+# Decompress archive.
 cd $TMP &&
 rm -rf $PKGNAME-$VERSION &&
 tar xzf $CWD/$PKGNAME-$VERSION.tar.gz &&
 cd $PKGNAME-$VERSION || exit 1
 
 # Apply ARCH specific patches.
-if [ "$ARCH" = "i386" ]; then
-  echo "${0##*/}: Applying any patches for $ARCH"
-  #cat $CWD/patches/foo.patch | patch -p0 --verbose
-elif [ "$ARCH" = "i486" ]; then
-  echo "${0##*/}: Applying any patches for $ARCH"
-  #cat $CWD/patches/foo.patch | patch -p0 --verbose
-elif [ "$ARCH" = "i586" ]; then
-  echo "${0##*/}: Applying any patches for $ARCH"
-  #cat $CWD/patches/foo.patch | patch -p0 --verbose
-elif [ "$ARCH" = "i686" ]; then
+if [ "$ARCH" = "i486" -o "$ARCH" = "i586" -o "$ARCH" = "i686" ]; then
   echo "${0##*/}: Applying any patches for $ARCH"
   #cat $CWD/patches/foo.patch | patch -p0 --verbose
 elif [ "$ARCH" = "x86_64" ]; then
@@ -128,54 +134,41 @@ elif [ "$ARCH" = "powerpc" ]; then
   #cat $CWD/patches/foo.patch | patch -p0 --verbose
 fi
 
-zcat ${CWD}/patches/bluez-utils-oui-usage.patch.gz | patch -p0 -E || exit 1
-zcat ${CWD}/patches/bluez-try-utf8-harder.patch.gz | patch -p1 -E || exit 1
-# http://thread.gmane.org/gmane.linux.bluez.kernel/1754
-zcat ${CWD}/patches/bluez-activate-wacom-mode2.patch.gz | patch -p1 -E || exit 1
+# Fix permissions for building.
+chown -R root:root .
+find . \
+  \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
+  -exec chmod 755 {} \; -o \
+  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
+  -exec chmod 644 {} \;
 
-## Fix permissions for building.
-chown -R root.root .
-find . -perm 664 -exec chmod 644 {} \;
-find . -perm 600 -exec chmod 644 {} \;
-find . -perm 444 -exec chmod 644 {} \;
-find . -perm 400 -exec chmod 644 {} \;
-find . -perm 440 -exec chmod 644 {} \;
-find . -perm 777 -exec chmod 755 {} \;
-find . -perm 775 -exec chmod 755 {} \;
-find . -perm 511 -exec chmod 755 {} \;
-find . -perm 711 -exec chmod 755 {} \;
-find . -perm 555 -exec chmod 755 {} \;
-
-## Configure, Tuning, GCC and Make options.
+# Configure, Tuning, GCC and Make options.
 CONFIGURE_FLAGS=${GSB_CONFIGURE_FLAGS:-""}
-if [ "$ARCH" = "i386" ]; then
+if [ "$ARCH" = "i486" -o "$ARCH" = "i586" ]; then
   TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2 -march=$ARCH -mtune=$TUNE"}
-elif [ "$ARCH" = "i486" ]; then
-  TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2 -march=$ARCH -mtune=$TUNE"}
-elif [ "$ARCH" = "i586" ]; then
-  TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O3 -march=$ARCH -mtune=$TUNE -pipe -fomit-frame-pointer"}
+  LIBDIRSUFFIX=""
 elif [ "$ARCH" = "i686" ]; then
-  TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O3 -march=$ARCH -mtune=$TUNE -pipe -fomit-frame-pointer"}
+  TUNE_CFLAGS="-O2 -march=i686 -mtune=i686"
+  LIBDIRSUFFIX=""
+elif [ "$ARCH" = "s390" ]; then
+  TUNE_CFLAGS="-O2"
+  LIBDIRSUFFIX=""
 elif [ "$ARCH" = "x86_64" ]; then
-  if [ "$TUNE" = "k8" -o "$TUNE" = "opteron" -o "$TUNE" = "athlon64" -o "$TUNE" = "athlon-fx" ]; then
-    TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O3 -march=$TUNE -mtune=$TUNE -pipe -fomit-frame-pointer -fPIC"}
-  else
-    TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O3 -march=k8 -mtune=k8 -pipe -fomit-frame-pointer -fPIC"}
-  fi
-  [ -z "$CONFIGURE_FLAGS" ] && {
-    CONFIGURE_FLAGS="--libdir=/usr/lib64"
-  }
+    TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2 -fPIC"}
+    LIBDIRSUFFIX="64"
 elif [ "$ARCH" = "powerpc" ]; then
   TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2 -march=$ARCH"}
-else
-  TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2"}
 fi
 EXTRA_CFLAGS=${GSB_EXTRA_CFLAGS:-""}
 MAKE_FLAGS=${GSB_MAKE_FLAGS:-""}
 
+# Configure
 CFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" CXXFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" \
   ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var \
-  --mandir=/usr/man $CONFIGURE_FLAGS --target=$ARCH-$DISTRO-linux \
+  --mandir=/usr/man $CONFIGURE_FLAGS \
+  --libdir=/usr/lib${LIBDIRSUFFIX} \
+  --build=$ARCH-$DISTRO-linux \
+  --target=$ARCH-$DISTRO-linux \
   --enable-shared \
   --disable-static \
   --enable-gstreamer \
@@ -196,65 +189,56 @@ CFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" CXXFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" \
   --enable-pcmciarules \
   || exit 1
 
-## Build and install.
+# Build and install.
 make $MAKE_FLAGS &&
 make $MAKE_FLAGS DESTDIR=$PKG install || exit 1
 
-mkdir -p $PKG/lib/udev/rules.d
-cat scripts/bluetooth.rules > $PKG/lib/udev/rules.d/60-bluetooth.rules
-rm -fr $PKG/etc/udev
+# Set udev rules
+mkdir -p $PKG/lib/udev/rules.d &&
+cat scripts/bluetooth-hid2hci.rules > $PKG/lib/udev/rules.d/60-bluetooth-hid2hci.rules &&
+cat scripts/bluetooth-serial.rules > $PKG/lib/udev/rules.d/60-bluetooth-serial.rules || exit 1
+rm -fr $PKG/etc/udev &&
 mkdir -p $PKG/lib/udev &&
-mv $PKG/usr/libexec/udev/bluetooth_serial $PKG/lib/udev ;
-rm -fr $PKG/usr/libexec ;
+mv $PKG/usr/libexec/udev/bluetooth_serial $PKG/lib/udev &&
+rm -fr $PKG/usr/libexec || exit 1
 
-## Users now can add themselves to the "netdev" group to use bluetooth.
+# Users now can add themselves to the "netdev" group to use bluetooth.
 sed -i "s/at_console=\"true\"/group=\"netdev\"/g" $PKG/etc/dbus-1/system.d/bluetooth.conf
 
-## compatibility for previous bluez-libs 3 package
+# compatibility for previous bluez-libs 3 package
 if [ "$ARCH" = "x86_64" ]; then
   ( cd $PKG/usr/lib64 ; ln -s libbluetooth.so libbluetooth.so.2 ) ;
 else
   ( cd $PKG/usr/lib ; ln -s libbluetooth.so libbluetooth.so.2 ) ;
 fi
 
-# Move/rename/patch init script:
-mv $PKG/etc/init.d $PKG/etc/rc.d
-mv $PKG/etc/rc.d/bluetooth $PKG/etc/rc.d/rc.bluetooth
 # Replace with our own Slackware version
-cp $CWD/rc.bluetooth $PKG/etc/rc.d/rc.bluetooth
+mv $PKG/etc/init.d $PKG/etc/rc.d &&
+mv $PKG/etc/rc.d/bluetooth $PKG/etc/rc.d/rc.bluetooth &&
+cp $CWD/rc.bluetooth $PKG/etc/rc.d/rc.bluetooth || exit 1
 
 # Edit "default" configuration script:
 sed -i "s:\(HIDD_ENABLE=\).*:\1false:" $PKG/etc/default/bluetooth || exit 1
 sed -i "s:\(HID2HCI_ENABLE=\).*:\1false:" $PKG/etc/default/bluetooth || exit 1
 
 # Install other configuration files:
-mkdir -p $PKG/etc/bluetooth
-cp -a audio/audio.conf $PKG/etc/bluetooth
-cp -a input/input.conf $PKG/etc/bluetooth
-cp -a network/network.conf $PKG/etc/bluetooth
-cp -a rfcomm/rfcomm.conf $PKG/etc/bluetooth
-chmod 644 $PKG/etc/bluetooth/*.conf
-
-# Install Debian's add-passkey program:
-if [ "$ARCH" = "x86_64" ]; then
-  DEBDEST=/usr/lib64/bluetooth
-else
-  DEBDEST=/usr/lib/bluetooth
-fi
-gcc $(pkg-config --libs --cflags dbus-1) -DDBUS_API_SUBJECT_TO_CHANGE \
-        $CWD/add-passkey.c -o $PKG/$DEBDEST/add-passkey || exit 1
-cp $CWD/register-passkeys $PKG/$DEBDEST
-chmod a+x $PKG/$DEBDEST/*
+mkdir -p $PKG/etc/bluetooth &&
+cp -a audio/audio.conf $PKG/etc/bluetooth &&
+cp -a input/input.conf $PKG/etc/bluetooth &&
+cp -a network/network.conf $PKG/etc/bluetooth &&
+cp -a rfcomm/rfcomm.conf $PKG/etc/bluetooth &&
+chmod 644 $PKG/etc/bluetooth/*.conf || exit 1
 
 # Default PIN (using "1234" seems insecure, so let's use an empty file instead):
-mkdir -p $PKG/etc/bluetooth/passkeys
-chmod 700 $PKG/etc/bluetooth/passkeys
-#echo "1234" > $PKG/etc/bluetooth/passkeys/default
-touch $PKG/etc/bluetooth/passkeys/default
+mkdir -p $PKG/etc/bluetooth/passkeys &&
+chmod 700 $PKG/etc/bluetooth/passkeys &&
+touch $PKG/etc/bluetooth/passkeys/default || exit 1
 
 # Do not overwrite configuration
 ( cd $PKG
   for file in \
+    etc/alsa/bluetooth.conf \
+    etc/dbus-1/system.d/bluetooth.conf \
     etc/bluetooth/audio.conf \
     etc/bluetooth/input.conf \
     etc/bluetooth/main.conf \
@@ -267,11 +251,11 @@ touch $PKG/etc/bluetooth/passkeys/default
   done
 )
 
-## Strip debugging symbols.
+# Strip debugging symbols.
 { find $PKG | xargs file | egrep "executable|shared object" | grep "ELF" | \
   cut -d: -f1 | xargs strip --strip-unneeded ; } 2>/dev/null
 
-## Compress and fix manpage links.
+# Compress and fix manpage links.
 [ -e $PKG/usr/man ] && {
   find $PKG/usr/man -type f -name \*.? -exec gzip -9f {} \;
   find $PKG/usr/man -type l -name \*.? -printf \
@@ -279,21 +263,24 @@ touch $PKG/etc/bluetooth/passkeys/default
      { rm -f '%f'; ln -sf '%l.gz' '%f.gz'; } );\n" | bash
 }
 
-## Deal with .info files.
+# Deal with .info files.
+[ -e $PKG/usr/share/info ] && {
+  mkdir -p $PKG/usr && mv $PKG/usr/share/info $PKG/usr || exit 1;
+  rmdir -p $PKG/usr/share
+  }
 [ -e $PKG/usr/info ] && {
   rm -f $PKG/usr/info/dir
   gzip -9 $PKG/usr/info/*.info
 }
 
-## Copy extra documentation into package.
+# Copy extra documentation into package.
 mkdir -p $PKG/usr/doc/$PKGNAME-$VERSION
-cp -a \
-  AUTHORS COPYING* ChangeLog NEWS README \
+cp -a AUTHORS COPYING COPYING.LIB README doc/*.txt \
   $PKG/usr/doc/$PKGNAME-$VERSION
 find $PKG/usr/doc/$PKGNAME-$VERSION/ -type f -exec chmod 644 {} \;
 chown -R root:root $PKG/usr/doc/$PKGNAME-$VERSION
 
-## Package meta files
+# Package meta files
 for FILE in doinst.sh slack-desc slack-required slack-conflicts slack-suggests
 do
   [ -e $CWD/$FILE ] && {
@@ -301,11 +288,11 @@ do
   }
 done
 
-## Create the package
+# Create the package
 cd $PKG
-makepkg -p -l y -c n $PKGDEST/$PKGNAME-${VERSION//-/_}-$ARCH-$BUILD.tgz
+makepkg -p -l y -c n $PKGDEST/$PKGNAME-${VERSION//-/_}-$ARCH-${BUILD}${TAG}.txz
 
-## Cleanup
+# Cleanup
 [ "$NOCLEANUP" = "0" ] && {
   rm -rf $PKG $TMP/$PKGNAME-$VERSION
 }
