* added package gettext-perl, required by anjuta 2.26 * update various devel versions

diff --git a/src/devel/mono-tools/mono-tools.SlackBuild b/src/devel/mono-tools/mono-tools.SlackBuild
--- a/src/devel/mono-tools/mono-tools.SlackBuild
+++ b/src/devel/mono-tools/mono-tools.SlackBuild
@@ -7,12 +7,12 @@
 ##
 
 ## Package variables.
-BUILD=3
-VERSION=2.0
+BUILD=1
+VERSION=2.4
 
 ## List any packages here that are required to build this package.
 ## The list is space seperated and case sensitive.
-REQUIRED_PACKAGES="mono monodoc gtk-sharp gnome-desktop-sharp gecko-sharp"
+REQUIRED_PACKAGES="mono gtk-sharp gnome-desktop-sharp gecko-sharp"
 
 ## Build variables.
 ARCH=${ARCH:-i586}
@@ -166,8 +166,13 @@ CFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" CXXFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" \
   || exit 1
 
 ## Build and install.
-make $MAKE_FLAGS &&
-make $MAKE_FLAGS DESTDIR=$PKG install || exit 1
+make $MAKE_FLAGS -j1 &&
+make $MAKE_FLAGS -j1 DESTDIR=$PKG install || exit 1
+
+## clean up man pages
+mv $PKG/usr/share/man/man1/mprof-decoder.1 $PKG/usr/man/man1/ &&
+mv $PKG/usr/share/man/man1/mprof-heap-viewer.1 $PKG/usr/man/man1/ || exit 1
+rmdir -p $PKG/usr/share/man/man1 
 
 # Fix for pkgconfig files on x86_64 platforms
 if [ "$ARCH" = "x86_64" ]; then
