proper faad2 patches. new SlackBuild.

diff --git a/src/libraries/faad2/faad2.SlackBuild b/src/libraries/faad2/faad2.SlackBuild
--- a/src/libraries/faad2/faad2.SlackBuild
+++ b/src/libraries/faad2/faad2.SlackBuild
@@ -1,108 +1,191 @@
 #!/bin/sh
 
+##
+## Package Variables
+##
+
+PKGNAME=`basename $0 .SlackBuild`
 CWD=`pwd`
 TMP=${TMP:-/tmp}
-PKG=$TMP/package-faad2
+PKG=$TMP/package-$PKGNAME
+PKG_DEST=/home/packages
+VERSION=${VERSION:-2.5}
+ARCH=${ARCH:-i686}
+BUILD=${BUILD:-1}
+DISTRO=${DISTRO:-slackware}
 
-VERSION=2.5
-ARCH=${ARCH:-i486}
-BUILD=1
-
-if [ -f /var/log/packages/faad2-$VERSION-$ARCH-$BUILD ]; then
-  echo "faad2-$VERSION-$ARCH-$BUILD package already installed"
+## Installation Check
+if [ -f /var/log/packages/${PKGNAME}-${VERSION}-${ARCH}-${BUILD} ]; then
+  echo "${PKGNAME}-${VERSION}-${ARCH}-${BUILD} package already installed"
   exit 0
 fi
 
+##
+## Temporary Space
+##
 if [ ! -d $TMP ]; then
-  mkdir -p $TMP # location to build the source
+  mkdir -p $TMP 
 fi
 rm -rf $PKG
 mkdir -p $PKG
 
+##
+## Build Options
+##
+
 if [ "$ARCH" = "i386" ]; then
-  SLKCFLAGS="-O2 -march=i386 -mtune=i686"
+  GSB_CFLAGS="-O2 -march=i386 -mtune=i386"
   ARCH_CONFIGURE=""
 elif [ "$ARCH" = "i486" ]; then
-  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
+  GSB_CFLAGS="-O2 -march=i486 -mtune=i486"
+  ARCH_CONFIGURE=""
+elif [ "$ARCH" = "i686" ]; then
+  GSB_CFLAGS="-O3 -march=i686 -mtune=i686 -pipe -fomit-frame-pointer -ffast-math"
   ARCH_CONFIGURE=""
 elif [ "$ARCH" = "powerpc" ]; then
-  SLKCFLAGS="-O2"
-  ARCH_CONFIGURE=""
-elif [ "$ARCH" = "s390" ]; then
-  SLKCFLAGS="-O2"
+  GSB_CFLAGS="-O2"
   ARCH_CONFIGURE=""
 elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-O2 -fPIC"
-  ARCH_CONFIGURE="--libdir=/usr/lib64 --without-xmms"
+  GSB_CFLAGS="-O3 -fPIC -pipe -fomit-frame-pointer -ffast-math"
+  ARCH_CONFIGURE="--libdir=/usr/lib64"
 fi
 
-cd $TMP
-rm -rf faad2
-unzip $CWD/faad2-"$VERSION".zip -d $TMP
-cd faad2
-bzcat $CWD/Makefile.am.faad2.patch.bz2 |patch -p0 --verbose
-cat $CWD/configure.in.mpeg4ip.patch |patch -p0 --verbose
-cat $CWD/virtual_definitions.patch |patch -p1 --verbose
-(
-cd common/mp4v2 
-cat $CWD/mp4atom-sliver.patch |patch -p0 --verbose
-)
+## Decompress archive
+cd $TMP 
+tar xzf $CWD/${PKGNAME}-${VERSION}.tar.gz
+cd $PKGNAME
 
-ex +":set ff=unix" +":wq" bootstrap
-ex +":set ff=unix" +":wq" configure.in
+
+### 
+### Cross-platform patches.  Faad2 is broken
+### with bmp/xmms plugins.  These patches remove
+### the building of these parts.
+
+patch -p0 < $CWD/patches/Makefile.am.diff
+patch -p0 < $CWD/patches/configure.in.diff
 
 # Apply $ARCH specific patches
 if [ "$ARCH" = "i386" ]; then
   echo "Applying patches for $ARCH"
-  #cat $CWD/foo.patch | patch -p0 --verbose
+  #cat $CWD/patches/foo.patch | patch -p0 --verbose
 elif [ "$ARCH" = "i486" ]; then
   echo "Applying patches for $ARCH"
-  #cat $CWD/foo.patch | patch -p0 --verbose
+  #cat $CWD/patches/foo.patch | patch -p0 --verbose
+elif [ "$ARCH" = "i686" ]; then
+  echo "Applying patches for $ARCH"
+  #cat $CWD/patches/foo.patch | patch -p0 --verbose
 elif [ "$ARCH" = "s390" ]; then
   echo "Applying patches for $ARCH"
-  #cat $CWD/foo.patch | patch -p0 --verbose
+  #cat $CWD/patches/foo.patch | patch -p0 --verbose
 elif [ "$ARCH" = "powerpc" ]; then
   echo "Applying patches for $ARCH"
-  #cat $CWD/foo.patch | patch -p0 --verbose
+  #cat $CWD/patches/foo.patch | patch -p0 --verbose
 elif [ "$ARCH" = "x86_64" ]; then
   echo "Applying patches for $ARCH"
-  #cat $CWD/foo.patch | patch -p0 --verbose
+  #cat $CWD/patches/foo.patch | patch -p0 --verbose
 fi
 
-chmod +x bootstrap
-sh ./bootstrap
-CFLAGS="$SLKCFLAGS" \
+##
+## Fix permissions for building
+##
+chown -R root.root .
+find . -perm 664 -exec chmod 644 {} \;
+find . -perm 600 -exec chmod 644 {} \;
+find . -perm 444 -exec chmod 644 {} \;
+find . -perm 400 -exec chmod 644 {} \;
+find . -perm 440 -exec chmod 644 {} \;
+find . -perm 777 -exec chmod 755 {} \;
+find . -perm 775 -exec chmod 755 {} \;
+find . -perm 511 -exec chmod 755 {} \;
+find . -perm 711 -exec chmod 755 {} \;
+find . -perm 555 -exec chmod 755 {} \;
+
+
+##
+## Run Configure and Build
+##
+## Add any local configuration options here.
+
+autoreconf -vif
+
+CFLAGS="$GSB_CFLAGS" \
+CXXFLAGS="$GSB_CFLAGS" \
 ./configure --prefix=/usr \
-	    --with-xmms \
-	    --with-mp4v2 \
-	    --with-drm \
             $ARCH_CONFIGURE \
-            $ARCH-slackware-linux || exit 1
+	    --sysconfdir=/etc \
+            --localstatedir=/var/lib \
+            --disable-static --enable-shared \
+	    --disable-xmms --disable-bmp \
+            --target=$ARCH-$DISTRO-linux || exit 1
 
-# some needed steps to get the xmms plugin
-make || exit 1
-make install
+make -j4 || exit 1
 make install DESTDIR=$PKG
-make uninstall
 
-mkdir -p $PKG/usr/doc/faad2-$VERSION
-cp -a AUTHORS COPYING ChangeLog NEWS README \
-  README.linux TODO $PKG/usr/doc/faad2-$VERSION
-chmod 644 $PKG/usr/doc/faad2-$VERSION/*
-chown root.root $PKG/usr/doc/faad2-$VERSION/*
+## Install Extra Documentation
+mkdir -p $PKG/usr/doc/$PKGNAME-$VERSION
+cp -a \
+  AUTHORS COPYING* ChangeLog NEWS README \
+  $PKG/usr/doc/$PKGNAME-$VERSION
+find $PKG/usr/doc/$PKGNAME-$VERSION/ -type f -exec chmod 644 {} \;
 
-find $PKG -type f | xargs file | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded
-gzip -9 $PKG/usr/man/*/*
+##
+##  Permissions
+##
+chown -R $(stat --format "%u:%g" /usr/sbin) $PKG/usr/bin
+chown -R root.root $PKG/usr/doc/$PKGNAME-$VERSION/*
 
+##
+## Strip Debugging Info
+##
+( cd $PKG
+  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
+  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
+)
+
+##
+## Compress and Link Manpages
+##
+if [ -d $PKG/usr/man ]; then
+  ( cd $PKG/usr/man
+    for manpagedir in $(find . -type d -name "man*") ; do
+      ( cd $manpagedir
+        for eachpage in $( find . -type l -maxdepth 1) ; do
+          ln -s $( readlink $eachpage ).gz $eachpage.gz
+          rm $eachpage
+        done
+        gzip -9 *.?
+      )
+    done
+  )
+fi
+
+##
+## Slackware Package Information
+##
 mkdir -p $PKG/install
-cat $CWD/slack-required > $PKG/install/slack-required
-cat $CWD/slack-desc > $PKG/install/slack-desc
+if [ -e $CWD/slack-required ]; then
+        cat $CWD/slack-required > $PKG/install/slack-required
+fi;
 
+if [ -e $CWD/slack-desc ]; then
+        cat $CWD/slack-desc > $PKG/install/slack-desc
+fi;
+
+if [ -e $CWD/doinst.sh ]; then
+        cat $CWD/doinst.sh > $PKG/install/doinst.sh
+fi;
+
+
+##
+## Make Slackware Package
+##
 cd $PKG
-makepkg -l y -c n $TMP/faad2-$VERSION-$ARCH-$BUILD.tgz
- 
-# Clean up the extra stuff:
+makepkg -l y -c n $PKG_DEST/$PKGNAME-$VERSION-$ARCH-$BUILD.tgz
+
+##
+## Cleanup If Wanted
+##
 if [ "$1" = "--cleanup" ]; then
-  rm -rf $TMP/faad2
+  rm -rf $TMP/$PKGNAME-$VERSION
   rm -rf $PKG
 fi
