svn checks.  Fixed stray VERSION in ffmpeg. Minor build order change.

diff --git a/src/libraries/ffmpeg/ffmpeg.SlackBuild b/src/libraries/ffmpeg/ffmpeg.SlackBuild
--- a/src/libraries/ffmpeg/ffmpeg.SlackBuild
+++ b/src/libraries/ffmpeg/ffmpeg.SlackBuild
@@ -29,9 +29,8 @@ This script is intended to be run from a working svn copy.
 
 EOF
 
-## Package variables.
+## Package variables. 
 BUILD=0
-VERSION=0.0.0
 
 ## List any packages here that are required to build this package.
 ## The list is space seperated and case sensitive.
@@ -51,6 +50,12 @@ CWD=$(pwd)
 NOCLEANUP=0
 FORCEBUILD=0
 SVN_REV=$(cd $PKGNAME && svn info 2> /dev/null | grep Revision | cut -d' ' -f2)
+
+if [ "$SVN_REV" = "" ] then
+  echo "Unable to properly check svn version. Please check your svn setup and try again."
+  exit 1;
+fi;
+
 echo "Building SVN_REV $SVN_REV"
 VERSION=${VERSION:-svn_$SVN_REV}
 
diff --git a/src/libraries/x264/x264.SlackBuild b/src/libraries/x264/x264.SlackBuild
--- a/src/libraries/x264/x264.SlackBuild
+++ b/src/libraries/x264/x264.SlackBuild
@@ -53,6 +53,11 @@ SVN_REV=$(cd $PKGNAME && svn info 2> /dev/null | grep Revision | cut -d' ' -f2)
 echo "Building SVN_REV $SVN_REV"
 VERSION=${VERSION:-svn_$SVN_REV}
 
+if [ "$SVN_REV" = "" ] then
+  echo "Unable to properly check svn version. Please check your svn setup and try again."
+  exit 1;
+fi;
+
 ## Usage.
 function usage() {
   cat << EOF
