Fix for yelp not to build against beagle. Added NetworkManager-vpn bindings for openvpn and vpnc

diff --git a/src/testing/NetworkManager-vpn/NetworkManager-vpn.SlackBuild b/src/testing/NetworkManager-vpn/NetworkManager-vpn.SlackBuild
--- a/src/testing/NetworkManager-vpn/NetworkManager-vpn.SlackBuild
+++ b/src/testing/NetworkManager-vpn/NetworkManager-vpn.SlackBuild
@@ -6,13 +6,48 @@
 ## Licenced under the terms of the GNU General Public Licence version 3.
 ##
 
+##
+## SVN Warning
+##
+
+cat << EOF
+
+*****************
+* Update Notice *
+*****************
+
+NetworkManager-vpn is built from the Networkmanager svn repository.  
+There are no released tarballs yet.  If you would like the latest code 
+for this package, please make sure to run "svn update" in the NetworkMager
+directory before compiling.  This build script will not update
+the repository automatically (in case specific revisions are wanted.)
+
+***** Note ************
+
+This script is intended to be run from a working svn copy.
+
+***********************
+
+EOF
+
 ## Package variables.
 BUILD=1
-VERSION=2.20.0
 
 ## List any packages here that are required to build this package.
 ## The list is space seperated and case sensitive.
-REQUIRED_PACKAGES="bzip2 GConf gnome-keyring gnome-vfs gtk+2 libglade libgnome libgnomecanvas libgnomeui libgpg-error"
+REQUIRED_PACKAGES="NetworkManager libnl wpa_supplicant libgcrypt dbus hal gtk+2 libglade gnome-keyring libgnomeui gnome-keyring wireless-tools glib2 iproute2 GConf gnome-common ppp"
+
+if [ ! -d ../NetworkManager/NetworkManager ]; then
+  echo "NetworkManager directory not found.  Are you building this script"
+  echo "within the GSB svn tree?"
+else
+  SVN_REV=$(cd ../NetworkManager/NetworkManager && svn info 2> /dev/null | grep Revision | cut -d' ' -f2)
+  if [ $? -ne 0 ]; then
+     echo "Cound not find svn information for NetworkManager.  Are you building"
+     echo "within the svn tree?"
+  fi;
+fi;
+  
 
 ## Build variables.
 ARCH=${ARCH:-i586}
@@ -27,6 +62,14 @@ PKG=$TMP/package-$PKGNAME
 CWD=$(pwd)
 NOCLEANUP=0
 FORCEBUILD=0
+
+if [ "$SVN_REV" = "" ]; then
+  echo "Unable to properly check svn version. Please check your svn setup and try again."
+  exit 1;
+fi;
+
+echo "Building SVN_REV $SVN_REV"
+VERSION=${VERSION:-svn_$SVN_REV}
 
 ## Usage.
 function usage() {
@@ -88,9 +131,10 @@ mkdir -p $PKG
 mkdir -p $PKG/install
 mkdir -p $PKGDEST
 
-## Decompress archive.
+## Copy SVN working copy to temporary space
+rm -fr $TMP/$PKGNAME-$VERSION ;
 cd $TMP &&
-tar xjf $CWD/$PKGNAME-$VERSION.tar.bz2 &&
+cp -ra $CWD/../NetworkManager/NetworkManager $PKGNAME-$VERSION &&
 cd $PKGNAME-$VERSION || exit 1
 
 # Apply ARCH specific patches.
@@ -144,7 +188,7 @@ elif [ "$ARCH" = "x86_64" ]; then
     TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O3 -march=k8 -mtune=k8 -pipe -fomit-frame-pointer -ffast-math -fPIC"}
   fi
   [ -z "$CONFIGURE_FLAGS" ] && {
-    CONFIGURE_FLAGS="--libdir=/usr/lib64"
+    CONFIGURE_FLAGS=""
   }
 elif [ "$ARCH" = "powerpc" ]; then
   TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2 -march=$ARCH"}
@@ -154,62 +198,67 @@ fi
 EXTRA_CFLAGS=${GSB_EXTRA_CFLAGS:-""}
 MAKE_FLAGS=${GSB_MAKE_FLAGS:-""}
 
+## We use the NetworkManager tree, but we only need to build from
+## within the vpn-daemons tree for the extentions.
+
+(
+cd vpn-daemons ;
+
+## We could also add in 'pptp' but it seems broken at the moment
+for i in openvpn vpnc ;
+
+do 
+
+(
+
+cd $i 
+
+echo "*** Building $i ***"
+
 ## Configure.
 CFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" CXXFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" \
-  ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var/lib \
+  ./autogen.sh --prefix=/usr --sysconfdir=/etc --localstatedir=/var/lib \
   $CONFIGURE_FLAGS --target=$ARCH-$DISTRO-linux \
   --disable-static --enable-shared \
-  --disable-schemas-install --with-gconf-schema-file-dir=/etc/gconf/schemas \
-  --with-gconf-source=`/usr/bin/gconftool-2 --get-default-source` \
-  --with-search=basic \
+  --with-distro=slackware \
+  --with-mdns-provider=avahi \
+  --with-ip=/sbin/ip \
+  --with-dbus-sys=/etc/dbus-1/system.d \
+  --enable-notification-icon \
   || exit 1
 
 ## Build and install.
-make $MAKE_FLAGS &&
+make &&
 make DESTDIR=$PKG install || exit 1
+
+mkdir -p $PKG/etc/dbus-1/system.d ;
+mkdir -p $PKG/etc/NetworkManager/VPN ;
+mkdir -p $PKG/usr/share/applications ;
+mkdir -p $PKG/usr/share/icons/gnome/48x48/mimetypes ;
+mkdir -p $PKG/usr/share/doc/$PKGNAME-$VERSION/$i
+
+cp nm-$i-service.conf $PKG/etc/dbus-1/system.d/nm-$i-service.conf.new ;
+cp nm-$i-service.name $PKG/etc/NetworkManager/VPN ;
+cp nm-$i.desktop $PKG/usr/share/applications ;
+cp gnome-mime-application-x-$i-settings.png $PKG/usr/share/icons/gnome/48x48/mimetypes ;
+
+cp README $PKG/usr/share/doc/$PKGNAME-$VERSION/$i
+cp doc/* $PKG/usr/share/doc/$PKGNAME-$VERSION/$i
+
+)
+
+done;
+
+)
+
+cp README ChangeLog AUTHORS NEWS $PKG/usr/share/doc/$PKGNAME-$VERSION/
+
+chown root.root $PKG/usr
+chown root.root $PKG/etc
 
 ## Strip debugging symbols.
 { find $PKG | xargs file | egrep "executable|shared object" | grep "ELF" | \
   cut -d: -f1 | xargs strip --strip-unneeded ; } 2>/dev/null
-
-## Compress and fix manpage links.
-[ -e $PKG/usr/man ] && {
-  find $PKG/usr/man -type f -name \*.? -exec gzip -9f {} \;
-  find $PKG/usr/man -type l -name \*.? -printf \
-    "( cd '%h'; [ -e '%l.gz' ] &&
-     { rm -f '%f'; ln -sf '%l.gz' '%f.gz'; } );\n" | bash
-}
-
-## Deal with .info files.
-[ -e $PKG/usr/info ] && {
-  rm -f $PKG/usr/info/dir
-  gzip -9 $PKG/usr/info/*.info
-}
-
-## Copy extra documentation into package.
-mkdir -p $PKG/usr/doc/$PKGNAME-$VERSION
-cp -a \
-  AUTHORS COPYING* ChangeLog NEWS README \
-  $PKG/usr/doc/$PKGNAME-$VERSION
-find $PKG/usr/doc/$PKGNAME-$VERSION/ -type f -exec chmod 644 {} \;
-chown -R root:root $PKG/usr/doc/$PKGNAME-$VERSION
-
-## Add schemas install to the doinst.sh if schemas are found.
-[ -d $PKG/etc/gconf/schemas ] && {
-  echo "if [ -x usr/bin/gconftool-2 ]; then" >>$PKG/install/doinst.sh
-  ( cd $PKG/etc/gconf/schemas
-    for FILE in *; do
-      [ -z "$(grep gconfentry $FILE)" ] && {
-        # Create gconf tree
-        echo "GCONF_CONFIG_SOURCE=\"\$(usr/bin/gconftool-2 --get-default-source)\" usr/bin/gconftool-2 --makefile-install-rule etc/gconf/schemas/$FILE >/dev/null 2>&1" >>$PKG/install/doinst.sh
-      } || {
-        # Load gconf settings
-        echo "GCONF_CONFIG_SOURCE=\"\$(usr/bin/gconftool-2 --get-default-source)\" usr/bin/gconftool-2 --config-source=\$(usr/bin/gconftool-2 --get-default-source) --direct --load etc/gconf/schemas/$FILE >/dev/null 2>&1" >>$PKG/install/doinst.sh
-      }
-    done
-  )
-  echo "fi" >>$PKG/install/doinst.sh
-}
 
 ## Package meta files
 for FILE in doinst.sh slack-desc slack-required slack-conflicts slack-suggests
@@ -219,9 +268,9 @@ do
   }
 done
 
-## Create the package
+## Create full package with vpn support
 cd $PKG
-makepkg -p -l y -c n $PKGDEST/$PKGNAME-${VERSION//-/_}-$ARCH-$BUILD.tgz
+makepkg -p -l y -c n $PKGDEST/$PKGNAME-0.7_${VERSION//-/_}-$ARCH-$BUILD.tgz
 
 ## Cleanup
 [ "$NOCLEANUP" = "0" ] && {
