SlackBuilds 1.4.  Minor improvements here and there. mpeg4ip and opal currently broken.

diff --git a/src/libraries/libgphoto2/libgphoto2.SlackBuild b/src/libraries/libgphoto2/libgphoto2.SlackBuild
--- a/src/libraries/libgphoto2/libgphoto2.SlackBuild
+++ b/src/libraries/libgphoto2/libgphoto2.SlackBuild
@@ -1,370 +1,214 @@
-#!/bin/sh
+#!/bin/bash
+## Version: 1.4 GSB SlackBuild.
+## Copyright (c) 2007 Darren 'Tadgy' Austin <darren (at) gnomeslackbuild.org>
+## Copyright (c) 2007 Steve Kennedy <sk238 (at) exeter.ac.uk>
+##
+## Licenced under the terms of the GNU General Public Licence version 3.
+##
 
-if [ `whoami` != "root" ]; then
-  echo "Need to run build script as root."
-  exit 1;
-fi;
-
-## Package defines
-PACKAGE=`basename $0 .SlackBuild`
+## Package variables.
 BUILD=1
-FORM=tar.gz
-ARCH=${ARCH:-x86_64_slamd64}
-BUILT_LOCATION=/home/packages/gnome
+VERSION=2.4.0
 
-## System defines
-CWD=`pwd`
+## List any packages here that are required to build this package.
+## The list is space seperated and case sensitive.
+REQUIRED_PACKAGES="libexif libjpeg libusb"
+
+## Build variables.
+ARCH=${ARCH:-i586}
+TUNE=${TUNE:-i586}
+DISTRO=${DISTRO:-slackware}
 TMP=${TMP:-/tmp}
-PKG=$TMP/package-$PACKAGE
+PKGDEST=${PKGDEST:-$TMP/gsb-packages}
 
-# Server stuff
-SERVER_NAME=${SERVER_NAME:-http://kent.dl.sourceforge.net}
-DIR_PATH=${DIR_PATH:-/sourceforge/gphoto/}
-INET_TIMEOUT=5
-WGET_OPTIONS="-c --timeout $INET_TIMEOUT -t 5 -w 10"
+## Script variables.
+PKGNAME=$(basename $0 .SlackBuild)
+PKG=$TMP/package-$PKGNAME
+CWD=$(pwd)
+NOCLEANUP=0
+FORCEBUILD=0
 
-# Build script defaults
-MIDPAUSE=yes
-INSTALL_PACKAGE=no
-QUIET=no
-MD5CHECK=yes
-if [ -f $CWD/version -a -s $CWD/version ]; then
-	VERSION=`cat $CWD/version`;
-	SKIPVER=yes
-else
-	SKIPVER=no
-fi;
-LOG=$CWD/$PACKAGE.build.log
+## Usage.
+function usage() {
+  cat << EOF
+Usage: ${0##*/} [options]
 
-# Some basic help
-usage() {
-cat << EOF
-options:      -help (this list)
-              -install (install package after building. default:no )
-	      -quiet (put all configure/make -j4 output to a log)
-	      -nomd5 (use this if there are no md5 checksums available)
-	      -skipver (skip the "LATEST" detect)
-	      -setbuild (set a specific build number)
-              -nopause (do not pause after building.  default: yes
-                        this allows an opportunity to double check the 
-                        install directories before creating the 
-                        package)
-
+Options:  -force        The package will not be built if a package of the same
+                        name is already installed, or any of the packages
+                        required to build are missing.  This option over-rides
+                        these checks and attempts a build anyway.
+          -no-cleanup   By default any temporary source, build and package
+                        directories will be deleted once the package is built.
+                        This option prevents those files from being removed.
+          -help         Show this help screen.
 EOF
 }
 
-# Check variables
-while [ 0 ]; do
-  if [ "$1" = "-nopause" ]; then
-    MIDPAUSE=no
-    shift 1
-  elif [ "$1" = "-install" ]; then
-    INSTALL_PACKAGE=yes
-    shift 1
-  elif [ "$1" = "-nomd5" ]; then
-    MD5CHECK=no
-    shift 1
-  elif [ "$1" = "-skipver" ]; then
-    SKIPVER="yes"
-    shift 1
-  elif [ "$1" = "-quiet" ]; then
-    QUIET="yes"
-    shift 1
-  elif [ "$1" = "-setbuild" ]; then
-	  shift 1
-	  BUILD=$1
-	  if [ -z $BUILD ]; then
-		  echo "Need to supply a build number."
-		  exit 1;
-          else
-		  echo "Setting build manually to $ARCH-$BUILD."
-	  fi;
-	  shift 1;
+## Parse command line arguments.
+while [ $# -gt 0 ]; do
+  if [ "$1" = "-force" ]; then
+    FORCEBUILD=1
+    shift
+  elif [ "$1" = "-no-cleanup" ]; then
+    NOCLEANUP=1
+    shift
   elif [ "$1" = "-help" ]; then
-    usage;
-    exit;
+    usage
+    exit 0
   else
-    break
+    echo "${0##*/}: Unknown option: $1"
+    exit 1
   fi
 done
 
-echo "*************************************************"
-echo "      Building $PACKAGE-$ARCH-$BUILD"
-echo "*************************************************"
-echo "Autoinstall: $INSTALL_PACKAGE"
-echo "Pause: $MIDPAUSE"
-if [ "$QUIET" = "yes" ]; then 
-	echo "Quiet: Logging to $CWD/$PACKAGE.build.log"; 
-fi;
-if [ "$SKIPVER" = "yes" ]; then 
-	echo "Version set manually to $VERSION."; 
-fi;
-if [ "$MD5CHECK" = "no" ]; then 
-	echo "Skipping MD5 Checks."; 
-fi;
+## Package requirements and installation checks.
+[ "$FORCEBUILD" = "0" ] && {
+  function check_installed() {
+    ls -1 /var/log/packages | grep "^${1}-[^-]*-[^-]*-[^-]*$" >/dev/null 2>&1
+    return $?
+  }
 
-echo
-## Discover latest package
-if [ "$SKIPVER" = "no" ]; then
-	echo -n "Running ncftp to find latest version of $PACKAGE: "
-	LATEST=`ncftpls -t $INET_TIMEOUT ${SERVER_NAME}/${DIR_PATH}/ | grep LATEST | sed -e 's/\@//g' | cut -f3 -d\-`
-	if [ $? != 0 ]; then
-		echo "Problem getting directory listing."
-		exit 1;
-	fi;
-	VERSION=$LATEST
-fi;
+  check_installed "$PKGNAME" && {
+    echo "${0##*/}: Remove installed '$PKGNAME' package before build."
+    exit 1
+  }
 
-if [ -z $LATEST ]; then
-	if [ -z $VERSION ]; then
-		echo "Can't figure out what version to use."
-		echo "You may have to set \$VERSION manually by creating a version file."
-		exit 1;
-	else
-		echo "There is no soft link indicating latest version on the server.  Using version set as $VERSION."
-	fi;
-fi;
-
-echo "Latest version is $VERSION."
-
-if [ "$MD5CHECK" = "no" ]; then
-	if [ -f $CWD/$PACKAGE-$VERSION.${FORM} ]; then
-		echo "We have the latest file."
-	else
-               	echo "Downloading latest source."
-               	wget $WGET_OPTIONS ${SERVER_NAME}${DIR_PATH}${PACKAGE}-${VERSION}.${FORM}
-	fi;
-else
-	if [ -f $CWD/${PACKAGE}-${VERSION}.${FORM} -a -f $CWD/${PACKAGE}-${VERSION}.md5sum ]; then
-		echo "We have the latest version of the source and checksums."
-	else
-               	echo "Downloading latest source and checksums."
-		wget $WGET_OPTIONS ${SERVER_NAME}${DIR_PATH}${PACKAGE}-${VERSION}.${FORM}
-		wget $WGET_OPTIONS ${SERVER_NAME}${DIR_PATH}${PACKAGE}-${VERSION}.md5sum
-	fi;
-fi;
-
-if [ "$MD5CHECK" = "yes" ]; then
-
-	if [ -f $CWD/$PACKAGE-$VERSION.${FORM} -a -f $CWD/$PACKAGE-$VERSION.md5sum ]; then
-        	echo "Running md5sum."
-        	cat  $CWD/$PACKAGE-$VERSION.md5sum | grep bz2 | md5sum -c - 
-        	if [ $? != 0 ]; then
-                	echo "Checksums failed."
-                	exit 1;
-        	fi;
-	else
-		echo "Files are missing."
-		exit 1;
-	fi;        
-fi;
-## Let's start making packages!
-##
-
-if [ -f /var/log/packages/$PACKAGE-$VERSION-$ARCH-$BUILD ]; then
-	echo
-  	echo "$PACKAGE-$VERSION-$ARCH-$BUILD package already installed"
-  	exit 0
-fi
-
-echo "Cleaning temporary space for build."
-mkdir -p $TMP # location to build the source
-rm -rf $PKG
-rm -fr $TMP/$PACKAGE-$VERSION
-mkdir -p $PKG # location for built binaries
-
-cd $TMP 
-echo "Extracing source tarball."
-if [ $FORM = "tar.bz2" ]; then
-        TAR_CMD="xfj"
-elif [ $FORM = "tar.gz" -o $FORM = "tgz" ]; then
-        TAR_CMD="xfz"
-fi; 
-
-tar $TAR_CMD $CWD/$PACKAGE-$VERSION.${FORM}
-if [ $? != 0 ]; then
-	echo "Tar extract failed.  Incomplete file?  Perhaps delete the tarball and try again."
-	exit 1;
-fi;
-
-cd $PACKAGE-$VERSION
-
-echo "Changing ownerships."
-chown -R root.root .
-find . -perm 666 -exec chmod 644 {} \;
-find . -perm 664 -exec chmod 644 {} \;
-
-# prebuild custom scripts
-if [ -x $CWD/prebuild.sh ]; then
-	. $CWD/prebuild.sh
-fi;
-
-run_configure() {
-echo "Running configure."
-CFLAGS="-O3 -fPIC -w" \
-./configure --prefix=/usr \
-            --libdir=/usr/lib64 \
-	    --enable-shared \
-            --disable-static \
-	    --disable-debug \
-	    --sysconfdir=/etc \
-	    --localstatedir=/var/lib \
-	    --libexecdir=/usr/bin \
-	    --with-gconf-source=`/usr/bin/gconftool-2 --get-default-source` \
-	      --with-gconf-schema-file-dir=/etc/gconf/schemas
-
-if [ $? != 0 ]; then
-	echo "Error running configure."
-	exit 1;
-fi;
+  for REQ in $REQUIRED_PACKAGES; do
+    check_installed "$REQ" || {
+      echo "${0##*/}: Required package '$REQ' not installed."
+      exit 1
+    }
+  done
 }
 
-
-if [ "$QUIET" = "yes" ]; then
-	run_configure > $LOG
-	## Run make
-	echo "Building."
-	make -j4 2>&1 >> $LOG 
-		if [ $? != 0 ];then
-			echo "Erroring running make."
-			exit 1;
-		fi;
-	make -j4 install DESTDIR=$PKG 2>&1 >> $LOG
-		if [ $? != 0 ];then
-			echo "Erroring running make."
-			exit 1;
-		fi;
-else
-	run_configure;
-	echo "Building."
-	make -j4 
-		if [ $? != 0 ];then
-			echo "Erroring running make."
-			exit 1;
-		fi;
-	make -j4 install DESTDIR=$PKG 
-		if [ $? != 0 ];then
-			echo "Erroring running make."
-			exit 1;
-		fi;
-
-fi;
-
-# Keep clean for scrollkeeper
-echo "Removing var..."
-rm -rf $PKG/var
-
-# Strangely, some install commands forget to set the
-# proper permissions
-echo "Fixing libraries in lib64..."
-chmod 755 $PKG/usr/lib64/*.la*
-chmod 755 $PKG/usr/lib64/*.so*
-
-# Run a custom script if you want for other
-# major tweaks (like fixing broken man pages, etc.
-if [ -x $CWD/custom.sh ]; then
-	echo "Running custom script..."
-	. $CWD/custom.sh
-fi;
-
-# Write schema install script if schemas exist
-# for post install , see below for doinst.sh
-if [ -d $PKG/etc/gconf/schemas ];
-then
-	echo "Schemas found. Writing installation script."
-	rm -f $CWD/schemainst.sh
-	( cd $PKG/etc/gconf/schemas;
-	for i in *;
-	do
-		if [ -z "`grep gconfentry $i`" ]; then
-			echo "echo \"Installing schema: $i\"" >> $CWD/schemainst.sh
-			echo "GCONF_CONFIG_SOURCE=\"`/usr/bin/gconftool-2 --get-default-source`\" /usr/bin/gconftool-2 --makefile-install-rule /etc/gconf/schemas/$i 2>&1 > /dev/null" >> $CWD/schemainst.sh
-		else
-			echo "echo \"Loading default schema: $i\"" >> $CWD/schemainst.sh
-			echo "GCONF_CONFIG_SOURCE=\"`/usr/bin/gconftool-2 --get-default-source`\" /usr/bin/gconftool-2 --config-source=`/usr/bin/gconftool-2 --get-default-source` --direct --load /etc/gconf/schemas/$i" >> $CWD/schemainst.sh
-		fi;
-	done;
-	)
-fi;
-
-# Some extraneous and generic documentation
-echo "Documentation."
-mkdir -p $PKG/usr/doc/$PACKAGE-$VERSION
-cp -a AUTHORS COPYING ChangeLog INSTALL NEWS README \
-  $PKG/usr/doc/$PACKAGE-$VERSION > /dev/null
-
-# Proper permissions
-echo "Fixing permissions."
-chown -R $(stat --format "%u:%g" /usr/sbin) $PKG/usr
-
-# Compress the man pages
-echo "Compressing man pages."
-if [ -d $PKG/usr/man ]; then 
-  gzip -9 $PKG/usr/man/*/*; 
-fi;
-if [ -d $PKG/usr/share/man ]; then 
-  gzip -9 $PKG/usr/share/man/*/*; 
-fi;
-if [ -d $PKG/usr/info ]; then 
-  gzip -9 $PKG/usr/info/*; 
-fi;
-
-# Strip debugging information
-echo "Stripping debug information."
-( cd $PKG
-  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
-  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
-)
-
-echo "Checking for broken soft links..."
-/home/stevek/devel/sk/linkcheck.pl $PKG
-
-# Slackware package info
-echo "Slackware package description and required files."
+## Temporary space and package storage.
+mkdir -p $TMP
+rm -rf $PKG
+mkdir -p $PKG
 mkdir -p $PKG/install
-if [ -e $CWD/slack-required ]; then
-	cat $CWD/slack-required > $PKG/install/slack-required
-fi;
-if [ -e $CWD/slack-desc ]; then
-	cat $CWD/slack-desc > $PKG/install/slack-desc
-fi;
-if [ -e $CWD/doinst.sh ]; then
-	if [ -f $CWD/schemainst.sh ]; then
-		cat $CWD/schemainst.sh > $PKG/install/doinst.sh
-	fi;
-	cat $CWD/doinst.sh >> $PKG/install/doinst.sh
-fi;
+mkdir -p $PKGDEST
 
-echo
+## Decompress archive.
+cd $TMP &&
+tar xjf $CWD/$PKGNAME-$VERSION.tar.bz2 &&
+cd $PKGNAME-$VERSION || exit 1
 
-# Any tweaks here
-if [ "$MIDPAUSE" = "yes" ]; then
-	echo
-	echo "PAUSE REQUESTED"
-	echo
-        echo "Make any additions to $PKG before pressing enter to"
-        echo "continue building packages."
-        read
-fi;
+# Apply ARCH specific patches.
+if [ "$ARCH" = "i386" ]; then
+  echo "${0##*/}: Applying any patches for $ARCH"
+  #cat $CWD/patches/foo.patch | patch -p0 --verbose
+elif [ "$ARCH" = "i486" ]; then
+  echo "${0##*/}: Applying any patches for $ARCH"
+  #cat $CWD/patches/foo.patch | patch -p0 --verbose
+elif [ "$ARCH" = "i586" ]; then
+  echo "${0##*/}: Applying any patches for $ARCH"
+  #cat $CWD/patches/foo.patch | patch -p0 --verbose
+elif [ "$ARCH" = "i686" ]; then
+  echo "${0##*/}: Applying any patches for $ARCH"
+  #cat $CWD/patches/foo.patch | patch -p0 --verbose
+elif [ "$ARCH" = "x86_64" ]; then
+  echo "${0##*/}: Applying any patches for $ARCH"
+  #cat $CWD/patches/foo.patch | patch -p0 --verbose
+elif [ "$ARCH" = "powerpc" ]; then
+  echo "${0##*/}: Applying any patches for $ARCH"
+  #cat $CWD/patches/foo.patch | patch -p0 --verbose
+fi
 
-# Make package
+## Fix permissions for building.
+chown -R root.root .
+find . -perm 664 -exec chmod 644 {} \;
+find . -perm 600 -exec chmod 644 {} \;
+find . -perm 444 -exec chmod 644 {} \;
+find . -perm 400 -exec chmod 644 {} \;
+find . -perm 440 -exec chmod 644 {} \;
+find . -perm 777 -exec chmod 755 {} \;
+find . -perm 775 -exec chmod 755 {} \;
+find . -perm 511 -exec chmod 755 {} \;
+find . -perm 711 -exec chmod 755 {} \;
+find . -perm 555 -exec chmod 755 {} \;
+
+## Configure, Tuning, GCC and Make options.
+CONFIGURE_FLAGS=${GSB_CONFIGURE_FLAGS:-""}
+if [ "$ARCH" = "i386" ]; then
+  TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2 -march=$ARCH -mtune=$TUNE"}
+elif [ "$ARCH" = "i486" ]; then
+  TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2 -march=$ARCH -mtune=$TUNE"}
+elif [ "$ARCH" = "i586" ]; then
+  TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O3 -march=$ARCH -mtune=$TUNE -pipe -fomit-frame-pointer -ffast-math"}
+elif [ "$ARCH" = "i686" ]; then
+  TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O3 -march=$ARCH -mtune=$TUNE -pipe -fomit-frame-pointer -ffast-math"}
+elif [ "$ARCH" = "x86_64" ]; then
+  if [ "$TUNE" = "k8" -o "$TUNE" = "opteron" -o "$TUNE" = "athlon64" -o "$TUNE" = "athlon-fx" ]; then
+    TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O3 -march=$TUNE -mtune=$TUNE -pipe -fomit-frame-pointer -ffast-math -fPIC"}
+  else
+    TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O3 -march=k8 -mtune=k8 -pipe -fomit-frame-pointer -ffast-math -fPIC"}
+  fi
+  [ -z "$CONFIGURE_FLAGS" ] && {
+    CONFIGURE_FLAGS="--libdir=/usr/lib64"
+  }
+elif [ "$ARCH" = "powerpc" ]; then
+  TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2 -march=$ARCH"}
+else
+  TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2"}
+fi
+EXTRA_CFLAGS=${GSB_EXTRA_CFLAGS:-""}
+MAKE_FLAGS=${GSB_MAKE_FLAGS:-""}
+
+## Configure.
+## The default is to build shared libraries, no static libraries, install into
+## /usr and use /etc as the config directory.
+## For packages with GNOME Schemas, additional options are required:
+##  --disable-schemas-install --with-gconf-schema-file-dir=/etc/gconf/schemas \
+##  --with-gconf-source=`/usr/bin/gconftool-2 --get-default-source` \
+CFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" CXXFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" \
+  ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var/lib \
+  $CONFIGURE_FLAGS --target=$ARCH-$DISTRO-linux \
+  --disable-static --enable-shared \
+  || exit 1
+
+## Build and install.
+make $MAKE_FLAGS &&
+make $MAKE_FLAGS DESTDIR=$PKG install || exit 1
+
+## Strip debugging symbols.
+{ find $PKG | xargs file | egrep "executable|shared object" | grep "ELF" | \
+  cut -d: -f1 | xargs strip --strip-unneeded ; } 2>/dev/null
+
+## Compress and fix manpage links.
+[ -e $PKG/usr/man ] && {
+  find $PKG/usr/man -type f -name \*.? -exec gzip -9f {} \;
+  find $PKG/usr/man -type l -name \*.? -printf \
+    "( cd '%h'; [ -e '%l.gz' ] &&
+     { rm -f '%f'; ln -sf '%l.gz' '%f.gz'; } );\n" | bash
+}
+
+## Deal with .info files.
+[ -e $PKG/usr/info ] && {
+  rm -f $PKG/usr/info/dir
+  gzip -9 $PKG/usr/info/*.info
+}
+
+## Copy extra documentation into package.
+mkdir -p $PKG/usr/doc/$PKGNAME-$VERSION
+cp -a \
+  AUTHORS COPYING* ChangeLog NEWS README \
+  $PKG/usr/doc/$PKGNAME-$VERSION
+find $PKG/usr/doc/$PKGNAME-$VERSION/ -type f -exec chmod 644 {} \;
+chown -R root:root $PKG/usr/doc/$PKGNAME-$VERSION
+
+## Package meta files
+for FILE in doinst.sh slack-desc slack-required slack-conflicts slack-suggests
+do
+  [ -e $CWD/$FILE ] && {
+    cat $CWD/$FILE >>$PKG/install/$FILE
+  }
+done
+
+## Create the package
 cd $PKG
-makepkg -l y -c n $TMP/$PACKAGE-$VERSION-$ARCH-$BUILD.tgz
-if [ "$INSTALL_PACKAGE" = "yes" ]; then
-	echo
-	echo "AUTOINSTALL REQUESTED"
-	echo
-	echo
-	upgradepkg --reinstall --install-new $TMP/$PACKAGE-$VERSION-$ARCH-$BUILD.tgz
-fi;
+makepkg -p -l y -c n $PKGDEST/$PKGNAME-${VERSION//-/_}-$ARCH-$BUILD.tgz
 
-echo
-echo "**** Moving package to $BUILT_LOCATION. ****"
-echo
-mkdir -p $BUILT_LOCATION
-mv $TMP/$PACKAGE-$VERSION-$ARCH-$BUILD.tgz $BUILT_LOCATION
-
-# Clean up
-echo "Cleaning up."
-rm -fr $TMP/$PACKAGE-$VERSION
-rm -fr $PKG
+## Cleanup
+[ "$NOCLEANUP" = "0" ] && {
+  rm -rf $PKG $TMP/$PKGNAME-$VERSION
+}
