update gir-repository for library building.

diff --git a/src/l/gir-repository/gir-repository.SlackBuild b/src/l/gir-repository/gir-repository.SlackBuild
--- a/src/l/gir-repository/gir-repository.SlackBuild
+++ b/src/l/gir-repository/gir-repository.SlackBuild
@@ -1,10 +1,7 @@
-#!/bin/bash
-# Version: 1.7 GSB Package SlackBuild.
-# Copyright (c) 2007,2008,2009 Darren 'Tadgy' Austin <darren (at) gnomeslackbuild.org>
-# Copyright (c) 2007,2008,2009 Steve Kennedy <steve (at) gnomeslackbuild.org>
+#!/bin/sh
+
+# Copyright (c) 2007-2011 Steve Kennedy <steve (at) gnomeslackbuild.org>
 # All rights reserved.
-#
-# Licenced under the terms of the GNU General Public Licence version 3.
 #
 # Redistribution and use of this script, with or without modification, is
 # permitted provided that the following conditions are met:
@@ -23,106 +20,109 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-# Package variables.
-BUILD=1
 VERSION=0.10.3
+GIRVERSION=0.10.3
+BUILD=1
 
-# List any packages here that are required to build this package.
-# The list is space seperated and case sensitive.
-REQUIRED_PACKAGES=""
-
-# Build variables.
 TAG=${TAG:-gsb}
 ARCH=${ARCH:-i486}
-TUNE=${TUNE:-i686}
 DISTRO=${DISTRO:-slackware}
 TMP=${TMP:-/tmp}
 PKGDEST=${PKGDEST:-$TMP}
-
-# Script variables.
-PKGNAME=$(basename $0 .SlackBuild)
-SRCNAME=gir-repository
-PKG=$TMP/package-$PKGNAME
+PKGNAM=gir-repository
+PKG=$TMP/package-$PKGNAM
 CWD=$(pwd)
-NOCLEANUP=0
-FORCEBUILD=0
 
-# Usage.
-function usage() {
-  cat << EOF
-Usage: ${0##*/} [options]
+# Source dir
+SRCDIR=$(cd $(dirname $0); pwd)
+# Packages to generate GIRs from
+SRCNAME[0]="gdk-pixbuf"
+SRCVERSION[0]="2.22.1"
+SRCURL[0]="ftp://ftp.gnome.org/pub/gnome/sources/gdk-pixbuf/2.22/gdk-pixbuf-${SRCVERSION[0]}.tar.bz2"
+MD5SUM[0]="716c4593ead3f9c8cca63b8b1907a561"
+SOURCE[0]="${SRCDIR}/${SRCNAME[0]}-${SRCVERSION[0]}.tar.bz2"
+SRCNAME[1]="pango"
+SRCVERSION[1]="1.28.3"
+SRCURL[1]="ftp://ftp.gnome.org/pub/gnome/sources/pango/1.28/pango-${SRCVERSION[1]}.tar.bz2"
+MD5SUM[1]="caa74baea47e7e16bc73c89f9089d522"
+SOURCE[1]="${SRCDIR}/${SRCNAME[1]}-${SRCVERSION[1]}.tar.bz2"
+SRCNAME[2]="atk"
+SRCVERSION[2]="1.32.0"
+SRCURL[2]="ftp://ftp.gnome.org/pub/gnome/sources/atk/1.32/atk-${SRCVERSION[2]}.tar.bz2"
+MD5SUM[2]="b9a19a3e426cd9ca930f0108c4ee343f"
+SOURCE[2]="${SRCDIR}/${SRCNAME[2]}-${SRCVERSION[2]}.tar.bz2"
 
-Options:  --force       The package will not be built if a package of the same
-                        name is already installed, or any of the packages
-                        required to build are missing.  This option over-rides
-                        these checks and attempts a build anyway.
-          --no-cleanup  By default any temporary source, build and package
-                        directories will be deleted once the package is built.
-                        This option prevents those files from being removed.
-          --help        Show this help screen.
-EOF
-}
-
-# Parse command line arguments.
-while [ $# -gt 0 ]; do
-  if [ "$1" = "-force" ] || [ "$1" = "--force" ]; then
-    FORCEBUILD=1
-    shift
-  elif [ "$1" = "-no-cleanup" ] || [ "$1" = "--no-cleanup" ]; then
-    NOCLEANUP=1
-    shift
-  elif [ "$1" = "-help" ] || [ "$1" = "--help" ]; then
-    usage
-    exit 0
-  else
-    echo "${0##*/}: Unknown option: $1"
-    exit 1
-  fi
-done
-
-# Package requirements and installation checks.
-[ "$FORCEBUILD" = "0" ] && {
-  function check_installed() {
-    ls -1 /var/log/packages | grep "^${1}-[^-]*-[^-]*-[^-]*$" >/dev/null 2>&1
-    return $?
-  }
-
-  check_installed "$PKGNAME" && {
-    echo "${0##*/}: Remove installed '$PKGNAME' package before build."
-    exit 1
-  }
-
-  for REQ in $REQUIRED_PACKAGES; do
-    check_installed "$REQ" || {
-      echo "${0##*/}: Required package '$REQ' not installed."
-      exit 1
-    }
-  done
-}
-
-# Temporary space and package storage.
 mkdir -p $TMP
 rm -rf $PKG
 mkdir -p $PKG
-mkdir -p $PKG/install
 mkdir -p $PKGDEST
+mkdir -p $TMP/${SRCNAME[$i]}
 
-# Install profile scripts: 
-cd $PKG ; tar xf $CWD/${SRCNAME}-${VERSION}-${ARCH}.txz &&
+for (( i = 0; i < ${#SOURCE[*]}; i++ )) ; do
+  # Download sources
+  if ! [ -f ${SOURCE[$i]} ]; then
+      wget -c -4 -T 20 -O "${SOURCE[$i]}" "${SRCURL[$i]}" || exit 1
+  fi;
+  echo "${MD5SUM[$i]}  ${SOURCE[$i]}" > $TMP/md5sum.${i}.$$
+  DOWNLOAD_ATTEMPT=0; VALID_MD5=0
+  until [ $DOWNLOAD_ATTEMPT -eq 3 -o $VALID_MD5 -eq 1 ]; do
+    # MD5SUM Comparison
+    if [ -f ${SOURCE[$i]} ]; then
+       md5sum -c $TMP/md5sum.${i}.$$ 2>/dev/null 1>/dev/null && VALID_MD5=1;
+    fi;
+    if [ "${VALID_MD5}" = "0" ]; then
+       # Download the source file
+      wget -c -4 -T 20 -O "${SOURCE[$i]}" "${SRCURL[$i]}" || {
+         echo ; echo "* Error: Failed to complete download."
+	 exit 1
+       }
+    fi
+    DOWNLOAD_ATTEMPT=$[$DOWNLOAD_ATTEMPT+1];
+    done;
+    rm -fr $TMP/md5sum.${i}.$$
 
-# Package meta files
-for FILE in doinst.sh slack-desc slack-required slack-conflicts slack-suggests
-do
-  [ -e $CWD/$FILE ] && {
-    cat $CWD/$FILE >>$PKG/install/$FILE
-  }
-done
+    if [ ! -f "${SOURCE[$i]}" -o ! -s "${SOURCE[$i]}" -o $VALID_MD5 -eq 0 ]; then
+      echo "File '$(basename ${SOURCE[$i]})' not available. Aborting the build."
+      exit 1
+    fi
 
-# Create the package
-cd $PKG
-makepkg -p -l y -c n $PKGDEST/$PKGNAME-${VERSION//-/_}-$ARCH-${BUILD}${TAG}.txz
+  cd $TMP &&
+  rm -rf ${SRCNAME[$i]}-${SRCVERSION[$i]} &&
+  tar xvf ${SOURCE[$i]} &&
+  cd ${SRCNAME[$i]}-${SRCVERSION[$i]} || exit 1
 
-# Cleanup
-if [ "$NOCLEANUP" = "0" ]; then
-  rm -rf $PKG $TMP/$PKGNAME-$VERSION
-fi;
+  chown -R root:root .
+  find . \
+    \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
+    -exec chmod 755 {} \; -o \
+    \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
+    -exec chmod 644 {} \;
+
+./configure --prefix=/usr \
+   --sysconfdir=/etc \
+   --mandir=/usr/man \
+   --libdir=/usr/lib${LIBDIRSUFFIX} \
+   --disable-static \
+   --enable-introspection=yes \
+    || exit 1
+
+make $NUMJOBS || make || exit 1
+make DESTDIR=$TMP/${SRCNAME[$i]} install || exit 1
+cd $TMP/${SRCNAME[$i]} || exit 1
+tar cf - --remove-files \
+$(find . -depth -type f -name "*.gir" \
+    -o -type f -name "*typelib" ) \
+  | ( cd ${PKG} ; tar xf - ) || exit 1
+rm -fr $TMP/${SRCNAME[$i]}
+done;
+
+mkdir -p $PKG/usr/doc/$PKGNAM-$VERSION
+cp -a $CWD/README.gir-repository \
+  $PKG/usr/doc/$PKGNAM-$VERSION
+find $PKG/usr/doc/$PKGNAM-$VERSION/ -type f -exec chmod 644 {} \;
+chown -R root:root $PKG/usr/doc/$PKGNAM-$VERSION
+
+mkdir -p $PKG/install 
+cat $CWD/slack-desc > $PKG/install/slack-desc
+
+cd $PKG ; makepkg -p -l y -c n $PKGDEST/${PKGNAM}-${VERSION}-$ARCH-${BUILD}${TAG}.txz || exit 1
