Office updates to SlackBuild 1.4.  Version changes, updated slack-desc, and reqs.

diff --git a/src/office/abiword/abiword.SlackBuild b/src/office/abiword/abiword.SlackBuild
--- a/src/office/abiword/abiword.SlackBuild
+++ b/src/office/abiword/abiword.SlackBuild
@@ -1,149 +1,228 @@
-#!/bin/sh
+#!/bin/bash
+## Version: 1.4 GSB SlackBuild.
+## Copyright (c) 2007 Darren 'Tadgy' Austin <darren (at) gnomeslackbuild.org>
+## Copyright (c) 2007 Steve Kennedy <sk238 (at) exeter.ac.uk>
+##
+## Licenced under the terms of the GNU General Public Licence version 3.
+##
 
-CWD=`pwd`
+## Package variables.
+BUILD=1
+VERSION=2.4.6
+
+## List any packages here that are required to build this package.
+## The list is space seperated and case sensitive.
+REQUIRED_PACKAGES="fribidi gucharmap nautilus enchant libxml2 libpng popt libjpeg"
+
+## Build variables.
+ARCH=${ARCH:-i586}
+TUNE=${TUNE:-i586}
+DISTRO=${DISTRO:-slackware}
 TMP=${TMP:-/tmp}
-PKG=$TMP/package-abiword
+PKGDEST=${PKGDEST:-$TMP/gsb-packages}
 
-VERSION=2.4.5
-ARCH=${ARCH:-i486}
-BUILD=4
+## Script variables.
+PKGNAME=$(basename $0 .SlackBuild)
+PKG=$TMP/package-$PKGNAME
+CWD=$(pwd)
+NOCLEANUP=0
+FORCEBUILD=0
 
-if [ -f /var/log/packages/abiword-$VERSION-$ARCH-$BUILD ]; then
-  echo "abiword-$VERSION-$ARCH-$BUILD package already installed"
-  exit 0
-fi
+## Usage.
+function usage() {
+  cat << EOF
+Usage: ${0##*/} [options]
 
-if [ ! -d $TMP ]; then
-  mkdir -p $TMP # location to build the source
-fi
+Options:  -force        The package will not be built if a package of the same
+                        name is already installed, or any of the packages
+                        required to build are missing.  This option over-rides
+                        these checks and attempts a build anyway.
+          -no-cleanup   By default any temporary source, build and package
+                        directories will be deleted once the package is built.
+                        This option prevents those files from being removed.
+          -help         Show this help screen.
+EOF
+}
+
+## Parse command line arguments.
+while [ $# -gt 0 ]; do
+  if [ "$1" = "-force" ]; then
+    FORCEBUILD=1
+    shift
+  elif [ "$1" = "-no-cleanup" ]; then
+    NOCLEANUP=1
+    shift
+  elif [ "$1" = "-help" ]; then
+    usage
+    exit 0
+  else
+    echo "${0##*/}: Unknown option: $1"
+    exit 1
+  fi
+done
+
+## Package requirements and installation checks.
+[ "$FORCEBUILD" = "0" ] && {
+  function check_installed() {
+    ls -1 /var/log/packages | grep "^${1}-[^-]*-[^-]*-[^-]*$" >/dev/null 2>&1
+    return $?
+  }
+
+  check_installed "$PKGNAME" && {
+    echo "${0##*/}: Remove installed '$PKGNAME' package before build."
+    exit 1
+  }
+
+  for REQ in $REQUIRED_PACKAGES; do
+    check_installed "$REQ" || {
+      echo "${0##*/}: Required package '$REQ' not installed."
+      exit 1
+    }
+  done
+}
+
+## Temporary space and package storage.
+mkdir -p $TMP
 rm -rf $PKG
 mkdir -p $PKG
-
-if [ "$ARCH" = "i386" ]; then
-  SLKCFLAGS="-O2 -march=i386 -mtune=i686"
-  ARCH_CONFIGURE=""
-elif [ "$ARCH" = "i486" ]; then
-  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
-  ARCH_CONFIGURE=""
-elif [ "$ARCH" = "powerpc" ]; then
-  SLKCFLAGS="-O2"
-  ARCH_CONFIGURE=""
-elif [ "$ARCH" = "s390" ]; then
-  SLKCFLAGS="-O2"
-  ARCH_CONFIGURE=""
-elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-O2 -fPIC"
-  ARCH_CONFIGURE="--libdir=/usr/lib64"
-fi
-
-cd $TMP 
-tar xzvf $CWD/abiword-$VERSION.tar.gz
-cd abiword-$VERSION
-
-#cat $CWD/abiword-2.3.4-pangographics.patch | patch -p1 --verbose
-cat $CWD/pango_xft.patch | patch -p1 --verbose
-
-# Apply $ARCH specific patches
-if [ "$ARCH" = "i386" ]; then
-  echo "Applying patches for $ARCH"
-  #cat $CWD/foo.patch | patch -p0 --verbose
-elif [ "$ARCH" = "i486" ]; then
-  echo "Applying patches for $ARCH"
-  #cat $CWD/foo.patch | patch -p0 --verbose
-elif [ "$ARCH" = "s390" ]; then
-  echo "Applying patches for $ARCH"
-  #cat $CWD/foo.patch | patch -p0 --verbose
-elif [ "$ARCH" = "powerpc" ]; then
-  echo "Applying patches for $ARCH"
-  #cat $CWD/foo.patch | patch -p0 --verbose
-elif [ "$ARCH" = "x86_64" ]; then
-  echo "Applying patches for $ARCH"
-  #cat $CWD/foo.patch | patch -p0 --verbose
-fi
-
-cd abi 
-#
-if [ ! -r configure ]; then
-  sh autogen.sh
-fi
-CFLAGS="$SLKCFLAGS" \
-./configure --prefix=/usr \
-	  --disable-static \
-          --sysconfdir=/etc \
-          --localstatedir=/var/lib \
-          --enable-gnome \
-	  --disable-static \
-	  --enable-extra-optimization \
-	  --enable-xft \
-	  --with-libxml2 \
-	  --enable-curl \
-	  --disable-magick \
-          $ARCH_CONFIGURE \
-	  $ARCH-slackware-linux || exit 1
-make || exit 1
-make install DESTDIR=$PKG
-
-cd ..
-
-cd abiword-plugins
-if [ ! -r configure ]; then
-  sh autogen.sh
-fi
-CFLAGS="$SLKCFLAGS" \
-./configure --prefix=/usr \
-          --disable-static \
-          --enable-gnome \
-          --enable-all \
-          $ARCH_CONFIGURE \
-          $ARCH-slackware-linux || exit 1
-make || exit 1
-make install DESTDIR=$PKG
-
-cd ..
-
-chown -R $(stat --format "%u:%g" /usr/sbin) $PKG/usr/bin
-
-mkdir -p $PKG/usr/share/pixmaps
-mv $PKG/usr/share/icons/abiword_48.png $PKG/usr/share/pixmaps
-(
-  cd $PKG/usr/share/icons/
-  ln -sf ../pixmaps/abiword_48.png .
-)
-
-cd abi
-mkdir -p $PKG/usr/doc/abiword-$VERSION/docs
-cp -a BUILD.TXT BiDiReadme.txt COPYING CREDITS.TXT README.TXT \
-  COPYRIGHT.TXT \
-  $PKG/usr/doc/abiword-$VERSION
-cp -a \
-  docs/*.abw \
-  $PKG/usr/doc/abiword-$VERSION/docs
-find $PKG/usr/doc/abiword-$VERSION/ -type f -exec chmod 644 {} \;
-(
-  cd ../abiword-docs/man
-  mkdir -p $PKG/usr/man/man8
-  cat abiword.8 | gzip -9c > $PKG/usr/man/man8/abiword.8.gz
-  cd ..
-  cp -a Manual/en/Abiword_Manual.abw $PKG/usr/doc/abiword-$VERSION/docs
-)
-chown -R root.root $PKG/usr/doc/abiword-$VERSION/*
-
-mkdir $PKG/usr/share/applications
-cat abiword.desktop > $PKG/usr/share/applications/abiword.desktop
-
-find $PKG -type f | xargs file | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded
-gzip -9 $PKG/usr/man/*/*
-
 mkdir -p $PKG/install
-cat $CWD/slack-required > $PKG/install/slack-required
-cat $CWD/slack-desc > $PKG/install/slack-desc
-cat $CWD/doinst.sh > $PKG/install/doinst.sh
+mkdir -p $PKGDEST
 
-cd $PKG
-makepkg -l y -c n $TMP/abiword-$VERSION-$ARCH-$BUILD.tgz
+## Decompress archive.
+cd $TMP &&
+tar xjf $CWD/$PKGNAME-$VERSION.tar.bz2 &&
+cd $PKGNAME-$VERSION || exit 1
 
-# Clean up the extra stuff:
-if [ "$1" = "--cleanup" ]; then
-  rm -rf $TMP/abiword-$VERSION
-  rm -rf $PKG
+# Apply ARCH specific patches.
+if [ "$ARCH" = "i386" ]; then
+  echo "${0##*/}: Applying any patches for $ARCH"
+  #cat $CWD/patches/foo.patch | patch -p0 --verbose
+elif [ "$ARCH" = "i486" ]; then
+  echo "${0##*/}: Applying any patches for $ARCH"
+  #cat $CWD/patches/foo.patch | patch -p0 --verbose
+elif [ "$ARCH" = "i586" ]; then
+  echo "${0##*/}: Applying any patches for $ARCH"
+  #cat $CWD/patches/foo.patch | patch -p0 --verbose
+elif [ "$ARCH" = "i686" ]; then
+  echo "${0##*/}: Applying any patches for $ARCH"
+  #cat $CWD/patches/foo.patch | patch -p0 --verbose
+elif [ "$ARCH" = "x86_64" ]; then
+  echo "${0##*/}: Applying any patches for $ARCH"
+  #cat $CWD/patches/foo.patch | patch -p0 --verbose
+elif [ "$ARCH" = "powerpc" ]; then
+  echo "${0##*/}: Applying any patches for $ARCH"
+  #cat $CWD/patches/foo.patch | patch -p0 --verbose
 fi
+
+## Fix permissions for building.
+chown -R root.root .
+find . -perm 664 -exec chmod 644 {} \;
+find . -perm 600 -exec chmod 644 {} \;
+find . -perm 444 -exec chmod 644 {} \;
+find . -perm 400 -exec chmod 644 {} \;
+find . -perm 440 -exec chmod 644 {} \;
+find . -perm 777 -exec chmod 755 {} \;
+find . -perm 775 -exec chmod 755 {} \;
+find . -perm 511 -exec chmod 755 {} \;
+find . -perm 711 -exec chmod 755 {} \;
+find . -perm 555 -exec chmod 755 {} \;
+
+## Configure, Tuning, GCC and Make options.
+CONFIGURE_FLAGS=${GSB_CONFIGURE_FLAGS:-""}
+if [ "$ARCH" = "i386" ]; then
+  TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2 -march=$ARCH -mtune=$TUNE"}
+elif [ "$ARCH" = "i486" ]; then
+  TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2 -march=$ARCH -mtune=$TUNE"}
+elif [ "$ARCH" = "i586" ]; then
+  TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O3 -march=$ARCH -mtune=$TUNE -pipe -fomit-frame-pointer -ffast-math"}
+elif [ "$ARCH" = "i686" ]; then
+  TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O3 -march=$ARCH -mtune=$TUNE -pipe -fomit-frame-pointer -ffast-math"}
+elif [ "$ARCH" = "x86_64" ]; then
+  if [ "$TUNE" = "k8" -o "$TUNE" = "opteron" -o "$TUNE" = "athlon64" -o "$TUNE" = "athlon-fx" ]; then
+    TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O3 -march=$TUNE -mtune=$TUNE -pipe -fomit-frame-pointer -ffast-math -fPIC"}
+  else
+    TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O3 -march=k8 -mtune=k8 -pipe -fomit-frame-pointer -ffast-math -fPIC"}
+  fi
+  [ -z "$CONFIGURE_FLAGS" ] && {
+    CONFIGURE_FLAGS="--libdir=/usr/lib64"
+  }
+elif [ "$ARCH" = "powerpc" ]; then
+  TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2 -march=$ARCH"}
+else
+  TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2"}
+fi
+EXTRA_CFLAGS=${GSB_EXTRA_CFLAGS:-""}
+MAKE_FLAGS=${GSB_MAKE_FLAGS:-""}
+
+## Configure.
+CFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" CXXFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" \
+  ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var/lib \
+  $CONFIGURE_FLAGS --target=$ARCH-$DISTRO-linux \
+  --disable-static --enable-shared \
+  --disable-schemas-install --with-gconf-schema-file-dir=/etc/gconf/schemas \
+  --with-gconf-source=`/usr/bin/gconftool-2 --get-default-source` \
+  || exit 1
+
+## Build and install.
+make $MAKE_FLAGS &&
+make $MAKE_FLAGS DESTDIR=$PKG install || exit 1
+
+## Strip debugging symbols.
+{ find $PKG | xargs file | egrep "executable|shared object" | grep "ELF" | \
+  cut -d: -f1 | xargs strip --strip-unneeded ; } 2>/dev/null
+
+## Compress and fix manpage links.
+[ -e $PKG/usr/man ] && {
+  find $PKG/usr/man -type f -name \*.? -exec gzip -9f {} \;
+  find $PKG/usr/man -type l -name \*.? -printf \
+    "( cd '%h'; [ -e '%l.gz' ] &&
+     { rm -f '%f'; ln -sf '%l.gz' '%f.gz'; } );\n" | bash
+}
+
+## Deal with .info files.
+[ -e $PKG/usr/info ] && {
+  rm -f $PKG/usr/info/dir
+  gzip -9 $PKG/usr/info/*.info
+}
+
+## Copy extra documentation into package.
+mkdir -p $PKG/usr/doc/$PKGNAME-$VERSION
+cp -a \
+  AUTHORS COPYING* ChangeLog NEWS README \
+  $PKG/usr/doc/$PKGNAME-$VERSION
+find $PKG/usr/doc/$PKGNAME-$VERSION/ -type f -exec chmod 644 {} \;
+chown -R root:root $PKG/usr/doc/$PKGNAME-$VERSION
+
+## Add schemas install to the doinst.sh if schemas are found.
+[ -d $PKG/etc/gconf/schemas ] && {
+  echo "if [ -x usr/bin/gconftool-2 ]; then" >>$PKG/install/doinst.sh
+  ( cd $PKG/etc/gconf/schemas
+    for FILE in *; do
+      [ -z "$(grep gconfentry $FILE)" ] && {
+        # Create gconf tree
+        echo "GCONF_CONFIG_SOURCE=\"\$(usr/bin/gconftool-2 --get-default-source)\" usr/bin/gconftool-2 --makefile-install-rule etc/gconf/schemas/$FILE >/dev/null 2>&1" >>$PKG/install/doinst.sh
+      } || {
+        # Load gconf settings
+        echo "GCONF_CONFIG_SOURCE=\"\$(usr/bin/gconftool-2 --get-default-source)\" usr/bin/gconftool-2 --config-source=\$(usr/bin/gconftool-2 --get-default-source) --direct --load etc/gconf/schemas/$FILE >/dev/null 2>&1" >>$PKG/install/doinst.sh
+      }
+    done
+  )
+  echo "fi" >>$PKG/install/doinst.sh
+}
+
+## Package meta files
+for FILE in doinst.sh slack-desc slack-required slack-conflicts slack-suggests
+do
+  [ -e $CWD/$FILE ] && {
+    cat $CWD/$FILE >>$PKG/install/$FILE
+  }
+done
+
+## Create the package
+cd $PKG
+makepkg -p -l y -c n $PKGDEST/$PKGNAME-${VERSION//-/_}-$ARCH-$BUILD.tgz
+
+## Cleanup
+[ "$NOCLEANUP" = "0" ] && {
+  rm -rf $PKG $TMP/$PKGNAME-$VERSION
+}
