* minor updates to a set

diff --git a/src/a/libcanberra/libcanberra.SlackBuild b/src/a/libcanberra/libcanberra.SlackBuild
--- a/src/a/libcanberra/libcanberra.SlackBuild
+++ b/src/a/libcanberra/libcanberra.SlackBuild
@@ -24,7 +24,7 @@
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 # Package variables.
-BUILD=4
+BUILD=5
 VERSION=0.12
 
 # List any packages here that are required to build this package.
@@ -157,6 +157,12 @@ fi
 EXTRA_CFLAGS=${GSB_EXTRA_CFLAGS:-""}
 MAKE_FLAGS=${GSB_MAKE_FLAGS:-""}
 
+# Check to make sure we have libtool-2 installed on the build machine 
+if [ ! -f /usr/lib${LIBDIRSUFFIX}/libltdl.so.7.2.0 ]; then
+  echo "Unable to find libltdl.so.7.2.0 for runtime.  Do you have libtool-2 installed?"
+  exit 1;
+fi;
+
 # Configure.
 CFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS -L/usr/libexec/libtool2/lib -I/usr/libexec/libtool2/include" \
 CXXFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" \
@@ -176,6 +182,13 @@ CXXFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" \
 # Build and install.
 make $MAKE_FLAGS &&
 make $MAKE_FLAGS DESTDIR=$PKG install || exit 1
+
+# Grab our own runtime copy of libtool-2 from the build machine; this way we 
+# don't have to supply a full package for one runtime library.
+cd $PKG/usr/lib${LIBDIRSUFFIX} &&
+cp /usr/lib${LIBDIRSUFFIX}/libltdl.so.7.2.0 . &&
+ln -s libltdl.so.7.2.0 libltdl.so.7 || exit 1
+cd $TMP/$PKGNAME-$VERSION
 
 # install freedesktop specification
 ( tar xfj $CWD/sound-theme-freedesktop-0.2.tar.bz2 &&
@@ -212,7 +225,7 @@ rm -fr $PKG/usr/share/doc
   gzip -9 $PKG/usr/info/*.info
 }
 
-## Copy extra documentation into package.
+# Copy extra documentation into package.
 mkdir -p $PKG/usr/doc/$PKGNAME-$VERSION
 cp -a LGPL README doc/{README,README.html,style.css} \
   $PKG/usr/doc/$PKGNAME-$VERSION
diff --git a/src/a/pulseaudio/pulseaudio.SlackBuild b/src/a/pulseaudio/pulseaudio.SlackBuild
--- a/src/a/pulseaudio/pulseaudio.SlackBuild
+++ b/src/a/pulseaudio/pulseaudio.SlackBuild
@@ -24,17 +24,17 @@
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 # Package variables.
-BUILD=2
+BUILD=3
 VERSION=0.9.15
 
 # List any packages here that are required to build this package.
 # The list is space seperated and case sensitive.
-REQUIRED_PACKAGES="libsndfile GConf hal avahi glib2 libsamplerate liboil bluez consolekit alsa-lib libtool-compat"
+REQUIRED_PACKAGES="libsndfile GConf hal avahi glib2 libsamplerate liboil bluez consolekit alsa-lib"
 
 # Build variables.
 TAG=${TAG:-gsb}
-ARCH=${ARCH:-i586}
-TUNE=${TUNE:-i586}
+ARCH=${ARCH:-i486}
+TUNE=${TUNE:-i486}
 DISTRO=${DISTRO:-slackware}
 TMP=${TMP:-/tmp}
 PKGDEST=${PKGDEST:-$TMP}
@@ -151,6 +151,12 @@ fi
 EXTRA_CFLAGS=${GSB_EXTRA_CFLAGS:-""}
 MAKE_FLAGS=${GSB_MAKE_FLAGS:-""}
 
+# Check to make sure we have libtool-2 installed on the build machine 
+if [ ! -f /usr/lib${LIBDIRSUFFIX}/libltdl.so.7.2.0 ]; then
+  echo "Unable to find libltdl.so.7.2.0 for runtime.  Do you have libtool-2 installed?"
+  exit 1;
+fi;
+
 # Configure.
 CFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS -L/usr/libexec/libtool2/lib -I/usr/libexec/libtool2/include" \
 CXXFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" \
@@ -175,6 +181,13 @@ make $MAKE_FLAGS -j1 || exit 1
 # strangely gets skipped. I almost went insane tracking this one down.  :/
 make $MAKE_FLAGS -j1 install DESTDIR=$PKG || exit 1
 
+# Grab our own runtime copy of libtool-2 from the build machine; this way we 
+# don't have to supply a full package for one runtime library.
+cd $PKG/usr/lib${LIBDIRSUFFIX} &&
+cp /usr/lib${LIBDIRSUFFIX}/libltdl.so.7.2.0 . &&
+ln -s libltdl.so.7.2.0 libltdl.so.7 || exit 1
+cd $TMP/$PKGNAME-$VERSION
+
 # Preserve settings
 mv $PKG/etc/pulse/daemon.conf $PKG/etc/pulse/daemon.conf.new || exit 1
 mv $PKG/etc/pulse/client.conf $PKG/etc/pulse/client.conf.new || exit 1
@@ -185,11 +198,6 @@ mkdir -p $PKG/etc/pulse
 # Move pulseaudio to GNOME specific xdg
 mkdir $PKG/etc/gnome &&
 mv $PKG/etc/xdg $PKG/etc/gnome || exit 1
-
-# Tweaks for x86_64 platforms
-#if [ "$ARCH" = "x86_64" ]; then
-  #sed -i "s:/lib/:/lib64/:g" $PKG/etc/pulse/default.pa.new || exit 1;
-#fi;
 
 # Strip debugging symbols.
 { find $PKG | xargs file | egrep "executable|shared object" | grep "ELF" | \
@@ -215,7 +223,7 @@ mv $PKG/etc/xdg $PKG/etc/gnome || exit 1
 
 # Copy extra documentation into package.
 mkdir -p $PKG/usr/doc/$PKGNAME-$VERSION
-cp -a GPL LICENSE README $CWD/docs/system_wide_daemon.txt \
+cp -a GPL LICENSE README \
   $PKG/usr/doc/$PKGNAME-$VERSION
 find $PKG/usr/doc/$PKGNAME-$VERSION/ -type f -exec chmod 644 {} \;
 chown -R root:root $PKG/usr/doc/$PKGNAME-$VERSION
