* whack of updates for library section in testing branch * updates of all SlackBuilds * added .info files for every package (a la slackbuilds.org), might be handy for users * some packages shifted locations * some doc fixes to packages

diff --git a/src/libraries/nss/nss.SlackBuild b/src/libraries/nss/nss.SlackBuild
--- a/src/libraries/nss/nss.SlackBuild
+++ b/src/libraries/nss/nss.SlackBuild
@@ -1,35 +1,53 @@
 #!/bin/bash
-## Version: 1.6 GSB Package SlackBuild.
-## Copyright (c) 2007 Darren 'Tadgy' Austin <darren (at) gnomeslackbuild.org>
-## Copyright (c) 2007 Steve Kennedy <sk238 (at) exeter.ac.uk>
-##
-## Licenced under the terms of the GNU General Public Licence version 3.
-##
+# Version: 1.7 GSB Package SlackBuild.
+# Copyright (c) 2007,2008,2009 Darren 'Tadgy' Austin <darren (at) gnomeslackbuild.org>
+# Copyright (c) 2007,2008,2009 Steve Kennedy <steve (at) gnomeslackbuild.org>
+# All rights reserved.
+#
+# Licenced under the terms of the GNU General Public Licence version 3.
+#
+# Redistribution and use of this script, with or without modification, is
+# permitted provided that the following conditions are met:
+#
+# 1. Redistributions of this script must retain the above copyright
+#    notice, this list of conditions and the following disclaimer.
+#
+#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
+#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
+#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
+#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
+#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
+#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
+#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
+#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
+#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
+#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-## Package variables.
-BUILD=1
+# Package variables.
+BUILD=3
 VERSION=3.12.3
-NSPR="nspr-4.7.4"
+NSPR_VERSION=4.7.4
 
-## List any packages here that are required to build this package.
-## The list is space seperated and case sensitive.
-REQUIRED_PACKAGES=""
+# List any packages here that are required to build this package.
+# The list is space seperated and case sensitive.
+REQUIRED_PACKAGES="gcc sqlite"
 
-## Build variables.
-ARCH=${ARCH:-i586}
-TUNE=${TUNE:-i586}
+# Build variables.
+TAG=${TAG:-gsb}
+ARCH=${ARCH:-i486}
+TUNE=${TUNE:-i486}
 DISTRO=${DISTRO:-slackware}
 TMP=${TMP:-/tmp}
 PKGDEST=${PKGDEST:-$TMP}
 
-## Script variables.
+# Script variables.
 PKGNAME=$(basename $0 .SlackBuild)
 PKG=$TMP/package-$PKGNAME
 CWD=$(pwd)
 NOCLEANUP=0
 FORCEBUILD=0
 
-## Usage.
+# Usage.
 function usage() {
   cat << EOF
 Usage: ${0##*/} [options]
@@ -45,7 +63,7 @@ Options:  --force       The package will not be built if a package of the same
 EOF
 }
 
-## Parse command line arguments.
+# Parse command line arguments.
 while [ $# -gt 0 ]; do
   if [ "$1" = "-force" ] || [ "$1" = "--force" ]; then
     FORCEBUILD=1
@@ -62,7 +80,7 @@ while [ $# -gt 0 ]; do
   fi
 done
 
-## Package requirements and installation checks.
+# Package requirements and installation checks.
 [ "$FORCEBUILD" = "0" ] && {
   function check_installed() {
     ls -1 /var/log/packages | grep "^${1}-[^-]*-[^-]*-[^-]*$" >/dev/null 2>&1
@@ -82,139 +100,110 @@ done
   done
 }
 
-## Temporary space and package storage.
+# Temporary space and package storage.
 mkdir -p $TMP
 rm -rf $PKG
 mkdir -p $PKG
 mkdir -p $PKG/install
 mkdir -p $PKGDEST
 
-## Decompress archive.
+# Decompress archive.
 rm -fr $PKGNAME-$VERSION;
 cd $TMP &&
 tar xfj $CWD/$PKGNAME-$VERSION.tar.bz2 &&
-tar xfz $CWD/$NSPR.tar.gz &&
-cp -r $NSPR/mozilla $PKGNAME-$VERSION &&
-rm -fr $TMP/$NSPR &&
+tar xfz $CWD/nspr-$NSPR_VERSION.tar.gz &&
+cp -r nspr-$NSPR_VERSION/mozilla $PKGNAME-$VERSION &&
+rm -fr $TMP/nspr-$NSPR_VERSION &&
 cd $PKGNAME-$VERSION || exit 1
 
 # Apply ARCH specific patches.
-if [ "$ARCH" = "i386" ]; then
+if [ "$ARCH" = "i486" -o "$ARCH" = "i586" -o "$ARCH" = "i686" ]; then
   echo "${0##*/}: Applying any patches for $ARCH"
-  #cat $CWD/patches/foo.patch | patch -p0 --verbose
-elif [ "$ARCH" = "i486" ]; then
-  echo "${0##*/}: Applying any patches for $ARCH"
-  #cat $CWD/patches/foo.patch | patch -p0 --verbose
-elif [ "$ARCH" = "i586" ]; then
-  echo "${0##*/}: Applying any patches for $ARCH"
-  #cat $CWD/patches/foo.patch | patch -p0 --verbose
-elif [ "$ARCH" = "i686" ]; then
-  echo "${0##*/}: Applying any patches for $ARCH"
-  #cat $CWD/patches/foo.patch | patch -p0 --verbose
+  zcat $CWD/patches/nss_disablezlib.patch | patch -p1 || exit 1
 elif [ "$ARCH" = "x86_64" ]; then
   echo "${0##*/}: Applying any patches for $ARCH"
-  #cat $CWD/patches/foo.patch | patch -p0 --verbose
+  zcat $CWD/patches/nss_disablezlib.patch | patch -p1 || exit 1
 elif [ "$ARCH" = "powerpc" ]; then
   echo "${0##*/}: Applying any patches for $ARCH"
-  #cat $CWD/patches/foo.patch | patch -p0 --verbose
+  zcat $CWD/patches/nss_disablezlib.patch | patch -p1 || exit 1
 fi
 
-## Fix permissions for building.
-chown -R root.root .
-find . -perm 664 -exec chmod 644 {} \;
-find . -perm 600 -exec chmod 644 {} \;
-find . -perm 444 -exec chmod 644 {} \;
-find . -perm 400 -exec chmod 644 {} \;
-find . -perm 440 -exec chmod 644 {} \;
-find . -perm 777 -exec chmod 755 {} \;
-find . -perm 775 -exec chmod 755 {} \;
-find . -perm 511 -exec chmod 755 {} \;
-find . -perm 711 -exec chmod 755 {} \;
-find . -perm 555 -exec chmod 755 {} \;
+# Fix permissions for building.
+chown -R root:root .
+find . \
+  \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
+  -exec chmod 755 {} \; -o \
+  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
+  -exec chmod 644 {} \;
 
-## Configure, Tuning, GCC and Make options.
+# Configure, Tuning, GCC and Make options.
 CONFIGURE_FLAGS=${GSB_CONFIGURE_FLAGS:-""}
-if [ "$ARCH" = "i386" ]; then
+if [ "$ARCH" = "i486" -o "$ARCH" = "i586" ]; then
   TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2 -march=$ARCH -mtune=$TUNE"}
-elif [ "$ARCH" = "i486" ]; then
-  TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2 -march=$ARCH -mtune=$TUNE"}
-elif [ "$ARCH" = "i586" ]; then
-  TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O3 -march=$ARCH -mtune=$TUNE -pipe -fomit-frame-pointer"}
+  LIBDIRSUFFIX=""
 elif [ "$ARCH" = "i686" ]; then
-  TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O3 -march=$ARCH -mtune=$TUNE -pipe -fomit-frame-pointer"}
-
+  TUNE_CFLAGS="-O2 -march=i686 -mtune=i686"
+  LIBDIRSUFFIX=""
+elif [ "$ARCH" = "s390" ]; then
+  TUNE_CFLAGS="-O2"
+  LIBDIRSUFFIX=""
 elif [ "$ARCH" = "x86_64" ]; then
-
-
-  if [ "$TUNE" = "k8" -o "$TUNE" = "opteron" -o "$TUNE" = "athlon64" -o "$TUNE" = "athlon-fx" ]; then
-    TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O3 -march=$TUNE -mtune=$TUNE -pipe -fomit-frame-pointer -fPIC"}
-  else
-    TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O3 -march=k8 -mtune=k8 -pipe -fomit-frame-pointer -fPIC"}
-  fi
-  [ -z "$CONFIGURE_FLAGS" ] && {
-    CONFIGURE_FLAGS="--libdir=/usr/lib64"
-  }
+    TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2 -fPIC"}
+    LIBDIRSUFFIX="64"
 elif [ "$ARCH" = "powerpc" ]; then
   TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2 -march=$ARCH"}
-else
-  TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2"}
 fi
 EXTRA_CFLAGS=${GSB_EXTRA_CFLAGS:-""}
 MAKE_FLAGS=${GSB_MAKE_FLAGS:-""}
 
-## Build and Install
-
+# Build and Install
 cd mozilla;
 
-## This variable is set because many of the commands are dependent on knowing 
-## the full path of certain directories. WORKINGDIR establishes a known path 
-## so that all others can be determined relative to this.
+# This variable is set because many of the commands are dependent on knowing 
+# the full path of certain directories. WORKINGDIR establishes a known path 
+# so that all others can be determined relative to this.
 WORKINGDIR=$PWD;
 echo "Working from $WORKINGDIR."
+echo "Compiling with: $TUNE_CFLAGS"
 
-
-## This variable is set so that the build is performed with no debugging symbols 
-## built into the binaries and that the default compiler optimizations are used.
+# This variable is set so that the build is performed with no debugging symbols 
+# built into the binaries and that the default compiler optimizations are used.
 export BUILD_OPT=1;
+export CC="gcc" ;
 
-## Default to lib on x86 platforms, but lib64 on x86_64
+# Default to lib on x86 platforms, but lib64 on x86_64
 if [ "$ARCH" = "x86_64" ]; then
-    NSSLIBDIR=lib64
-    ##
-    ## Required Make Flags for x86_64
-    ##
     export USE_64=1
     export MAKE_FLAGS="USE_64=1"
     echo $MAKE_FLAGS;
-else
-    NSSLIBDIR=lib;
 fi;
-
+NSSLIBDIR="lib${LIBDIRSUFFIX}"
 cd security/nss ;
-
-## Build and install.
+# Build and install.
 export NS_USE_GCC=1
 export NSS_USE_SYSTEM_SQLITE=1
-CFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" CXXFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" \
-   make nss_build_all || exit 1;
-
+export CFLAGS="${TUNE_CFLAGS} $EXTRA_CFLAGS"
+export CXXFLAGS="${TUNE_CFLAGS} $EXTRA_CFLAGS"
+make BUILD_OPT=1 CC="gcc" NS_USE_GCC=1 NSS_USE_SYSTEM_SQLITE=1 \
+   ${MAKE_FLAGS} nss_build_all || exit 1;
 cd ../../;
-
-NSS_LINUXDIR=`basename $(ls -d $WORKINGDIR/dist/Linux*) 1`;
-
+NSS_LINUXDIR=$(basename $(ls -d $WORKINGDIR/dist/Linux*) 1);
 echo "Installing from $NSS_LINUXDIR."
+
+# Clean up environment
+unset NS_USE_GCC
+unset NSS_USE_SYSTEM_SQLITE
+unset CFLAGS
+unset CXXFLAGS
+unset CC
 
 mkdir -p $PKG/usr/bin
 mkdir -p $PKG/usr/include
-
 install -v -m755 -d $PKG/usr/$NSSLIBDIR/pkgconfig ;
-
 sed -e "s:@LIBDIR@:$NSSLIBDIR:g" $CWD/pkgconfig/nspr.pc > \
        $PKG/usr/$NSSLIBDIR/pkgconfig/nspr.pc || exit 1
-
 sed -e "s:@LIBDIR@:$NSSLIBDIR:g" $CWD/pkgconfig/nss.pc > \
        $PKG/usr/$NSSLIBDIR/pkgconfig/nss.pc  || exit 1
-
 chmod 644 $PKG/usr/$NSSLIBDIR/pkgconfig/nspr.pc
 chmod 644 $PKG/usr/$NSSLIBDIR/pkgconfig/nss.pc
 chown root:root $PKG/usr/$NSSLIBDIR/pkgconfig/nspr.pc
@@ -222,25 +211,21 @@ chown root:root $PKG/usr/$NSSLIBDIR/pkgconfig/nss.pc
 mkdir -p $PKG/usr/bin
 install -v -m755 $CWD/pkgconfig/nss-config $PKG/usr/bin &&
 install -v -m755 $CWD/pkgconfig/nspr-config $PKG/usr/bin || exit 1
-
 cd dist ;
-
 install -v -m755 $NSS_LINUXDIR/lib/*.so $PKG/usr/$NSSLIBDIR &&
 install -v -m644 $NSS_LINUXDIR/lib/{*.chk,libcrmf.a} $PKG/usr/$NSSLIBDIR &&
 install -v -m755 -d $PKG/usr/include/{nss,nspr} &&
 install -v -m644 {public,private}/nss/* $PKG/usr/include/nss || exit 1
 install -v -m755 $NSS_LINUXDIR/bin/{certutil,cmsutil,crlutil,modutil,pk12util,signtool,signver,ssltap,addbuiltin} $PKG/usr/bin || exit 1
-
 cp -v -RL $NSS_LINUXDIR/include/* $PKG/usr/include/nspr &&
 chmod -v 644 $PKG/usr/include/nspr/prvrsion.h || exit 1
+# End of Build and Install;
 
-## End of Build and Install;
-
-## Strip debugging symbols.
+# Strip debugging symbols.
 { find $PKG | xargs file | egrep "executable|shared object" | grep "ELF" | \
   cut -d: -f1 | xargs strip --strip-unneeded ; } 2>/dev/null
 
-## Compress and fix manpage links.
+# Compress and fix manpage links.
 [ -e $PKG/usr/man ] && {
   find $PKG/usr/man -type f -name \*.? -exec gzip -9f {} \;
   find $PKG/usr/man -type l -name \*.? -printf \
@@ -248,7 +233,28 @@ chmod -v 644 $PKG/usr/include/nspr/prvrsion.h || exit 1
      { rm -f '%f'; ln -sf '%l.gz' '%f.gz'; } );\n" | bash
 }
 
-## Package meta files
+# Deal with .info files.
+[ -e $PKG/usr/share/info ] && {
+  mkdir -p $PKG/usr && mv $PKG/usr/share/info $PKG/usr || exit 1;
+  rmdir -p $PKG/usr/share
+  }
+[ -e $PKG/usr/info ] && {
+  rm -f $PKG/usr/info/dir
+  gzip -9 $PKG/usr/info/*.info
+}
+
+# Copy extra documentation into package.
+mkdir -p $PKG/usr/doc/$PKGNAME-$VERSION
+cd $TMP/$PKGNAME-$VERSION
+find . -name LICENSE -exec cat {} \; >> $PKG/usr/doc/$PKGNAME-$VERSION/LICENSE
+find . -name README -exec cat {} \; >> $PKG/usr/doc/$PKGNAME-$VERSION/README
+cp -a ./mozilla/security/nss/lib/freebl/mpi/tests/LICENSE-MPL \
+      /mozilla/security/nss/trademarks.txt \
+      $PKG/usr/doc/$PKGNAME-$VERSION
+find $PKG/usr/doc/$PKGNAME-$VERSION/ -type f -exec chmod 644 {} \;
+chown -R root:root $PKG/usr/doc/$PKGNAME-$VERSION
+
+# Package meta files
 for FILE in doinst.sh slack-desc slack-required slack-conflicts slack-suggests
 do
   [ -e $CWD/$FILE ] && {
@@ -256,11 +262,11 @@ do
   }
 done
 
-## Create the package
+# Create the package
 cd $PKG
-makepkg -p -l y -c n $PKGDEST/$PKGNAME-${VERSION//-/_}-$ARCH-$BUILD.tgz
+makepkg -p -l y -c n $PKGDEST/$PKGNAME-${VERSION//-/_}-$ARCH-${BUILD}${TAG}.txz
 
-## Cleanup
+# Cleanup
 [ "$NOCLEANUP" = "0" ] && {
   rm -rf $PKG $TMP/$PKGNAME-$VERSION
 }
