Force --with-testing for /testing/ packages.
This will help keep the build machine clean of extraneous packages when
building normal packages.

diff --git a/build/buildgsb b/build/buildgsb
--- a/build/buildgsb
+++ b/build/buildgsb
@@ -1,5 +1,5 @@
 #!/bin/bash
-# Version: 1.9.2 GNOME SlackBuild Build Script
+# Version: 1.9.3 GNOME SlackBuild Build Script
 # Copyright (c) 2007, 2008, 2009
 #   Darren 'Tadgy' Austin <darren (at) gnomeslackbuild.org>, Coventry, UK.
 #   Steve Kennedy <steve (at) gnomeslackbuild.org>
@@ -62,9 +62,6 @@ LOGSDIR=${LOGSDIR:-$TMP/gsb${GSB_ARCH}-buildlogs}
 
 # Location of our build source
 BUILDSOURCE=${BUILDSOURCE:-"${BASH_SOURCE%/*}/../src"}
-EXTRASOURCE=${EXTRASOURCE:-"${BASH_SOURCE%/*}/../"}
-PASTURESOURCE=${PASTURESOURCE:-"${BASH_SOURCE%/*}/../"}
-TESTINGSOURCE=${TESTINGSOURCE:-"${BASH_SOURCE%/*}/../"}
 
 # GPG-KEY
 GPGKEY=${GPGKEY:-"${BUILDSOURCE}/../GPG-KEY"}
@@ -97,7 +94,6 @@ WITH_TEST_PACKAGES=0
 # We check md5sums to cover ourselves. 
 WGET_OPTIONS="--no-check-certificate"
 
-
 #========================================================================
 # COMMAND LINE PARSING 
 #
@@ -127,10 +123,6 @@ while [ -n "$1" ] ; do
     -publish|--publish)
       PUBLISH=1
       SKIP_REBUILDS=1
-      shift
-    ;;
-    -verify|--verify)
-      VERIFY=1
       shift
     ;;
     -with-testing|--with-testing)
@@ -172,8 +164,8 @@ done
 # STARTUP
 echo ; header "* Building GSB "
 if [ "$(id -u)" != "0" ]; then
-echo "* Error: Only root can build, install, upgrade, or remove packages."
-exit 1
+  echo "* Error: Only root can build, install, upgrade, or remove packages."
+  exit 1
 fi
 
 # Temporary space, package and log file storage.
@@ -184,8 +176,9 @@ mkdir -p $PKGDEST/${EXTRADIR} &&
 mkdir -p $PKGDEST/${PASTUREDIR} &&
 mkdir -p $PKGDEST/${TESTINGDIR} &&
 mkdir -p $PKGDEST/${PATCHESDIR} || exit 1
+
 # Clear away all tagfiles from build tree to prevent some applications
-# from being skipped
+# from being skipped when upgradepkg is called.
 find $PKGDEST/ -name tagfile -exec rm {} \;
 
 #========================================================================
@@ -197,13 +190,32 @@ find $PKGDEST/ -name tagfile -exec rm {} \;
 cd ${BUILDSOURCE}
 BUILDLIST=${BUILDLIST:-""}
 [ -f buildlist.txt ] && {
-BUILDLIST="${BUILDLIST:-$( egrep -v "^#|^$" buildlist.txt | cut -d'#' -f1 )}"
+BUILDLIST="$(egrep -v "^#|^$" buildlist.txt | \
+  # Remove our testing packages if not specified.
+  if [ "$WITH_TEST_PACKAGES" = "1" ]; then cat ; else egrep -v testing; fi;)"
 }
+
+#========================================================================
+# CLEAN SYSTEM OF TESTING/ PACKAGES
+#
+# Clear the system of any packages from testing/ which might be lying around.
+# This ensures that we don't accidently build against a package we don't want.
+#
+if [ "$WITH_TEST_PACKAGES" = "0" ]; then
+  echo; header "Removing any test packages."
+( cd ${BUILDSOURCE}/../testing &&
+  for testpkg in $(find . -type d -mindepth 1 -maxdepth 1); do
+    removepkg $testpkg 1>/dev/null 2>/dev/null
+  done;
+)
+fi;
 
 #========================================================================
 # MAIN BUILD LOOP
 #
 # Do the build.
+
+echo; header "* Starting build."; echo;
 
 # LOOP THROUGH ALL PACKAGES IN $BUILDLIST
 for listitem in $BUILDLIST ;
@@ -221,17 +233,17 @@ SOURCE=$BUILDSOURCE
 case $SET in
    extra)
      SUBDIR=$GSBDIR/../${EXTRADIR}/${PACKAGE}
-     SOURCE=$EXTRASOURCE
+     SOURCE=$BUILDSOURCE/../
      NOPATCHES=1
      ;;
    pasture)
      SUBDIR=$GSBDIR/../${PASTUREDIR}
-     SOURCE=$PASTURESOURCE
+     SOURCE=$BUILDSOURCE/../
      NOPATCHES=1
      ;;
    testing)
      SUBDIR=$GSBDIR/../${TESTINGDIR}/packages
-     SOURCE=$TESTINGSOURCE
+     SOURCE=$BUILDSOURCE/../
      NOPATCHES=1
      ;;
    *)
@@ -415,50 +427,6 @@ fi;
 # Done our PACKAGES loop
 done 
 
-#========================================================================
-# VERIFY SET CONTENTS
-#
-# Make sure our PACKAGESDIR has the same number of packages as found in our
-# source directory if we are publishing. We don't want to overlook anything. 
-# 
-if [ "${VERIFY}" = "1" ]; then
-  echo ; echogreen "* " ; echo -n "Verifying contents of set $SET: " 
-  # Make sure we only have the number of packages identical to the number in 
-  # the source directory
-  PKGS_FOUND=$( find_package_files "${PKGDEST}/${GSBDIR}/${SET}" "" \
-      "" "" "" "\.txz" )
-  if [ "$(echo ${PKGS_FOUND} | wc -w)" -ne "$(echo $BUILDLIST | wc -w )" ]; then
-    echo $PKGS_FOUND >> ${TMP}/pkgsfound$$
-    echo $BUILDLIST >> ${TMP}/buildlist$$
-    for PKG in $PKGS_FOUND ; do 
-      [ -f $PKG.asc ] || {
-        echo ; echo "WARNING: $(package_name $PKG) exists without a signature."
-      }
-      [ -f "${PKG//.txz/.txt}" ] || {
-        echo ; echo "WARNING: $(package_name $PKG) does not have a text description."
-      }
-      PKGNAME=$(package_name $PKG)
-      [ -z "$(grep ${PKGNAME} ${TMP}/buildlist$$ )" ] && { 
-         PKG_NOT_IN_BUILDLIST="${PKG_ERRORS} ${PKGNAME}"
-      }
-      [ -z "$(grep $BUILDLIST ${TMP}/pkgsfound$$ )" ] && { 
-         PKG_NOT_IN_TREE="${PKG_ERRORS} ${PKGNAME}"
-      }
-    done;
-    rm ${TMP}/pkgsfound$$
-    rm ${TMP}/buildlist$$
-    echo ; header "* Error: Package contents differ."
-    [ -z ${PKG_NOT_IN_BUILDLIST} ] || {
-       echo "The following packages were found, but not in the buildlist: ${PKG_NOT_IN_BUILDLIST}"
-    }
-    [ -z ${PKG_NOT_IN_TREE} ] || {
-       echo "The following packages were not found, but in the buildlist: ${PKG_NOT_IN_TREE}"
-    }
-    exit 1;
-  fi;
-  echo "contents of ${SET} seem ok."
-fi;
-
 # Break out if there has been an error.
 [ "$?" != "0" ] && {
   exit 1
@@ -505,7 +473,9 @@ EOF
 
 # Copy extra documentation
 cp extra/README.TXT $PKGDEST/$EXTRADIR || exit 1
-cp testing/README.TXT $PKGDEST/$TESTINGDIR || exit 1
+[ "$WITH_TEST_PACKAGES" = "1" ] && {
+  cp testing/README.TXT $PKGDEST/$TESTINGDIR || exit 1
+}
 if [ "$ARCH" = "x86_64" ]; then
   cp ChangeLog.slackware64 $PKGDEST/ChangeLog.txt &&
   cp VERSIONS.slackware64 $PKGDEST/VERSIONS || exit 1
@@ -526,8 +496,11 @@ if [ "${PUBLISH}" = "1" ]; then
   echo ; header "* Generating package file lists and checksums."
   ( 
   cd $PKGDEST &&
-    for DIR in $GSBDIR $PATCHESDIR $EXTRADIR \
-          $SOURCEDIR $PASTUREDIR $TESTINGDIR ;
+    PUBLISH_DIRS="$GSBDIR $PATCHESDIR $EXTRADIR $SOURCEDIR $PASTUREDIR"
+    [ "$WITH_TEST_PACKAGES" = "1" ] && {
+       PUBLISH_DIRS="${PUBLISH_DIRS} $TESTINGDIR"
+    }
+    for DIR in "${PUBLISH_DIRS}"
     do
       [ -d $DIR ] && {
         # Skip making packages for our source/
