* update gnome-menus for ooo 3.1 * add set tagfiles * upgrade slapt-get and gslapt * testing ooo langpack build * minor tweaks to documentation

diff --git a/src/ooo/openoffice3/openoffice3.SlackBuild b/src/ooo/openoffice3/openoffice3.SlackBuild
--- a/src/ooo/openoffice3/openoffice3.SlackBuild
+++ b/src/ooo/openoffice3/openoffice3.SlackBuild
@@ -26,10 +26,15 @@
 # Package variables.
 BUILD=1
 VERSION=3.1.1.1
+WITH_LANGUAGES=${WITH_LANGUAGES:-"YES"}
+LANGUAGES="en-GB de fr it ar da el es fi he hi-IN hu ja ko \
+           nb nl pl pt ro ru sv th tr uk zh-CN zh-TW"
 
 # List any packages here that are required to build this package.
 REQUIRED_PACKAGES="gtk+2 libgnomeui neon libsndfile gnome-vfs boost libgnomeui mozilla-xulrunner nss sane zlib librsvg libjpeg jre nss jdk apache-ant"
 
+# We will want to build with gtk/kde and native widgets.
+KDE_REQUIRED_PACKAGES="kdebase-workspace kdelibs qt"
 
 # Build variables.
 TAG=${TAG:-gsb}
@@ -97,6 +102,12 @@ done
       exit 1
     }
   done
+  for REQ in $KDE_REQUIRED_PACKAGES; do
+    check_installed "$REQ" || {
+      echo "${0##*/}: KDE package '$REQ' required for build to stay compatible with Slackware."
+      slapt-get --install $REQ || exit 1
+    }
+  done
 }
 
 # Temporary space and package storage.
@@ -108,7 +119,7 @@ mkdir -p $PKGDEST
 
 # Decompress archive.
 cd $TMP &&
-tar xzf $CWD/ooo-build-$VERSION.tar.gz &&
+#tar xzf $CWD/ooo-build-$VERSION.tar.gz &&
 cd ooo-build-$VERSION || exit 1
 
 # Apply ARCH specific patches.
@@ -124,12 +135,12 @@ elif [ "$ARCH" = "powerpc" ]; then
 fi
 
 # Fix permissions for building.
-chown -R root:root .
-find . \
-  \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
-  -exec chmod 755 {} \; -o \
-  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
-  -exec chmod 644 {} \;
+#chown -R root:root .
+#find . \
+  #\( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
+  #-exec chmod 755 {} \; -o \
+  #\( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
+  #-exec chmod 644 {} \;
 
 # Configure, Tuning, GCC and Make options.
 CONFIGURE_FLAGS=${GSB_CONFIGURE_FLAGS:-""}
@@ -158,14 +169,26 @@ zcat $CWD/ooo-build.gsb.diff.gz | patch -p1
 # We need to temporarily spam a directory on the build machine
 mkdir -p /usr/share/openclipart
 [ -z "${ANT_HOME}" ] && . /etc/profile.d/ant.sh
+[ -f "/etc/profile.d/qt4.sh" ] && . /etc/profile.d/qt4.sh
+export QTDIR="${QT4DIR}"
+export QTINC="$QTDIR/include"
+export QTLIB="$QTDIR/lib"
+
+# Support multiple languages
+if [ "${WITH_LANGUAGES}" = "YES" ]; then
+  LANGUAGES="en-US ${LANGUAGES}"
+else
+  LANGUAGES="en-US"
+fi;
 
 CFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" CXXFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" \
   ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var/lib \
-  --mandir=/usr/man $CONFIGURE_FLAGS \
+  --mandir=/usr/man \
+  $CONFIGURE_FLAGS \
+  --with-lang="${LANGUAGES}" \
   --libdir=/usr/lib${LIBDIRSUFFIX} \
   --with-distro=GNOMESlackBuild${LIBDIRSUFFIX} \
   --with-ant-home=/usr/lib${LIBDIRSUFFIX}/apache-ant \
-  --with-lang="en-US en-GB de fr it ar da el es fi he hi-IN hu ja ko nb nl pl pt-BR ro ru sv th tr uk zh-CN zh-TW" \
   --disable-odk \
   --disable-pam \
   --disable-pam-link \
@@ -173,16 +196,15 @@ CFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" CXXFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" \
   --enable-access \
   --enable-cairo \
   --disable-kde \
-  --disable-kde4 \
+  --enable-kde4 \
   --enable-gtk \
   --with-system-cairo \
   --with-system-neon \
   --with-system-icu \
   --with-system-expat \
   --with-system-boost \
-  --with-system-mozilla=libxul \
+  --with-system-mozilla \
   --disable-mono \
-  --enable-openxml \
   --with-binsuffix=3.1 \
   --with-docdir=/usr/share/doc/openoffice.org \
   --with-gcc-speedup=ccache \
@@ -194,7 +216,7 @@ CFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" CXXFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" \
 for i in $CWD/{ooo_*,ooo-cli*,ooo310*,lib*,biblio*,extras*,mdbtools*} ; do 
   if [ ! -f ./src/${i} ]; then
     echo "Linking to source tree: $(basename $i)"
-    (cd src ; ln -s $i )
+    (cd src ; ln -fs $i )
   fi;
 done; echo
 
@@ -205,32 +227,30 @@ make || exit 1
 cd bin ; OODESTDIR=$PKG ./package-ooo || exit 1
 
 # Split out language packs
-cd $PKG ; 
-LANGUAGES="en-GB de fr it ar da el es fi he hi-IN hu ja ko \
-           nb nl pl pt-BR ro ru sv th tr uk zh-CN zh-TW"
-for lang in $LANGUAGES ; do
-  echo "Splitting langpack $lang."
-  (
-  mkdir -p $TMP/$PKGNAME-l10n-$lang ;
-  tar cf - --remove-files $(find . -name "README*$lang*" \
-                 -o -name "LICENSE*${lang}*" \
-		 -o -name "*${lang}.res" \
-		 -o -name "*${lang}.dat" \
-		 -o -name "*${lang}.xcu" \
-		 -o -name "*${lang}.soe" \
-		 -o -name "*${lang}.sog" \
-		 -o -name "*${lang}.soh" \
-		 -o -name "*${lang}.oxt" \
-		 -o -name "${lang}") \
-		 | ( cd $TMP/$PKGNAME-l10n-$lang ; tar xf - )
-  mkdir -p $TMP/$PKGNAME-l10n-$lang/install &&
-  cat $CWD/l10n/slack-desc.openoffice3-l10n-${lang} > \
-    $TMP/$PKGNAME-l10n-$lang/install/slack-desc ;
-  ( cd $TMP/$PKGNAME-l10n-$lang ;
-    makepkg -p -l y -c n $PKGDEST/$PKGNAME-l10n-${lang}-${VERSION//-/_}-noarch-${BUILD}${TAG}.txz)
-  )
-  rm -fr $TMP/$PKGNAME-l10n-$lang ;
-done;
+if [ "${WITH_LANGUAGES}" = "YES" ]; then
+  cd $PKG ; 
+  for lang in ${LANGUAGES//en-US/} ; do
+    echo "Splitting langpack $lang."
+    (
+    mkdir -p $TMP/$PKGNAME-l10n-$lang ;
+    tar cf - --remove-files $(find . -name "README*$lang*" \
+                   -o -name "LICENSE*${lang}*" \
+		   -o -type d -name "${lang}" \
+		   -o -name "Lang_*${lang}.xba" \
+                   -o -name "Langpack-${lang}.xcu" \
+		   -o -name "*${lang}.oxt" ) | ( cd $TMP/$PKGNAME-l10n-$lang ; tar xf - )
+    mkdir -p $TMP/$PKGNAME-l10n-$lang/install &&
+    cat $CWD/l10n/slack-desc.openoffice3-l10n-${lang} > \
+      $TMP/$PKGNAME-l10n-$lang/install/slack-desc ;
+    # doinst dictionary installation
+    cat $CWD/doinst-l10n.sh | sed "s,@LIBDIRSUFFIX@,${LIBDIRSUFFIX},g" \
+      | sed "s,@LANG@,${lang//en-GB/en},g" > $TMP/$PKGNAME-l10n-$lang/install/doinst.sh ;
+    ( cd $TMP/$PKGNAME-l10n-$lang ;
+      makepkg -p -l y -c n $PKGDEST/$PKGNAME-l10n-${lang}-${VERSION//-/_}-noarch-${BUILD}${TAG}.txz)
+    )
+    rm -fr $TMP/$PKGNAME-l10n-$lang ;
+  done;
+fi;
 
 # Add /usr/share/pixmaps directory and link icons to it
 mkdir -p $PKG/usr/pixmaps
@@ -284,5 +304,9 @@ makepkg -p -l y -c n $PKGDEST/$PKGNAME-${VERSION//-/_}-$ARCH-${BUILD}${TAG}.txz 
 
 # Cleanup
 [ "$NOCLEANUP" = "0" ] && {
-  rm -rf $PKG $TMP/ooo-build-$VERSION
+  echo "no deleting"
+  #rm -rf $PKG $TMP/ooo-build-$VERSION
+  # Make sure to clean up build machine of any kde packages to prevent 
+  # unwanted dependencies. 
+  #removepkg $KDE_REQUIRED_PACKAGES
 }
