* change from ooo2 to ooo3 (latest stable) * update gnome-menus-ooo

diff --git a/src/ooo/openoffice3/openoffice3.SlackBuild b/src/ooo/openoffice3/openoffice3.SlackBuild
--- a/src/ooo/openoffice3/openoffice3.SlackBuild
+++ b/src/ooo/openoffice3/openoffice3.SlackBuild
@@ -8,18 +8,24 @@
 
 ## Package variables.
 BUILD=1
-VERSION=1.25
+VERSION=3.0.1.3
 
 ## List any packages here that are required to build this package.
-## The list is space seperated and case sensitive.
-REQUIRED_PACKAGES="perl gzip zlib"
+## We build with mono/java support on x86.  x86_64 does not yet support
+## this configuration.
+if [ "$ARCH" = "x86_64" ]; then
+  REQUIRED_PACKAGES="gtk+2 libgnomeui neon libsndfile gnome-vfs boost libgnomeui mozilla-xulrunner nss sane zlib librsvg libjpeg nss"
+else
+  REQUIRED_PACKAGES="gtk+2 libgnomeui neon libsndfile gnome-vfs boost libgnomeui mozilla-xulrunner nss sane zlib librsvg libjpeg jre nss jdk apache-ant"
+fi;
+
 
 ## Build variables.
 ARCH=${ARCH:-i586}
 TUNE=${TUNE:-i586}
 DISTRO=${DISTRO:-slackware}
 TMP=${TMP:-/tmp}
-PKGDEST=${PKGDEST:-$TMP/gsb-tree/packages}
+PKGDEST=${PKGDEST:-$TMP}
 
 ## Script variables.
 PKGNAME=$(basename $0 .SlackBuild)
@@ -82,12 +88,19 @@ done
 }
 
 ## Temporary space and package storage.
-mkdir -p $TMP/$PKGNAME
+mkdir -p $TMP
 rm -rf $PKG
 mkdir -p $PKG
 mkdir -p $PKG/install
 mkdir -p $PKGDEST
 
+## Decompress archive.
+cd $TMP &&
+# Disabled in case build fails;  ooo-build can
+# resume broken builds.
+#rm -rf $PKGNAME-$VERSION &&
+tar xzf $CWD/ooo-build-$VERSION.tar.gz &&
+cd ooo-build-$VERSION || exit 1
 
 # Apply ARCH specific patches.
 if [ "$ARCH" = "i386" ]; then
@@ -117,21 +130,24 @@ if [ "$ARCH" = "i386" ]; then
 elif [ "$ARCH" = "i486" ]; then
   TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2 -march=$ARCH -mtune=$TUNE"}
 elif [ "$ARCH" = "i586" ]; then
-  TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2 -march=$ARCH -mtune=$TUNE -pipe -fomit-frame-pointer"}
+  TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O3 -march=$ARCH -mtune=$TUNE -pipe -fomit-frame-pointer"}
 elif [ "$ARCH" = "i686" ]; then
-  TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2 -march=$ARCH -mtune=$TUNE -pipe -fomit-frame-pointer"}
+  TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O3 -march=$ARCH -mtune=$TUNE -pipe -fomit-frame-pointer"}
 elif [ "$ARCH" = "x86_64" ]; then
   LIBDIR=lib64
   if [ "$TUNE" = "k8" -o "$TUNE" = "opteron" -o "$TUNE" = "athlon64" -o "$TUNE" = "athlon-fx" ]; then
-    TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2 -march=$TUNE -mtune=$TUNE -pipe -fomit-frame-pointer -fPIC"}
+    TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O3 -march=$TUNE -mtune=$TUNE -pipe -fomit-frame-pointer -fPIC"}
   else
-    TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2 -march=k8 -mtune=k8 -pipe -fomit-frame-pointer -fPIC"}
+    TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O3 -march=k8 -mtune=k8 -pipe -fomit-frame-pointer -fPIC"}
   fi
   [ -z "$CONFIGURE_FLAGS" ] && {
-    CONFIGURE_FLAGS="--libdir=/usr/lib64"
+    CONFIGURE_FLAGS="--libdir=/usr/lib64 --with-num-cpus=2 --without-java --disable-mono"
   }
 elif [ "$ARCH" = "powerpc" ]; then
   TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2 -march=$ARCH"}
+  [ -z "$CONFIGURE_FLAGS" ] && {
+    CONFIGURE_FLAGS="--with-arch=ppc"
+  }
 else
   TUNE_CFLAGS=${GSB_TUNE_CFLAGS:-"-O2"}
 fi
@@ -139,70 +155,97 @@ EXTRA_CFLAGS=${GSB_EXTRA_CFLAGS:-""}
 MAKE_FLAGS=${GSB_MAKE_FLAGS:-""}
 LIBDIR=${LIBDIR:-"lib"}
 
-## Build and install.
+## Add GNOMESlackBuild sections to go-oo configure system
+#cp $CWD/gsb_art/*.bmp ./src || exit 1
+cp $CWD/patches/GNOMESlackBuild* ./distro-configs || exit 1
+patch -p1 < $CWD/patches/addgsb-$VERSION.patch || exit 1
 
-# This is a list of the perl modules with version numbers to include
-# in our package
-MODULE_LIST="IO-Compress-Base-2.015 Compress-Raw-Zlib-2.017 IO-Compress-Zlib-2.015 Compress-Zlib-2.015 Archive-Zip-1.25"
+## We need to temporarily spam a directory on the build machine
+mkdir -p /usr/share/openclipart
 
-PERL_ARCH=$(perl -v | grep This | cut -d' ' -f 7)
-PERL_VERSION=$(perl -v | grep This | cut -d' ' -f4 | cut -dv -f2)
+## Set our distro configuration
+if [ "$ARCH" = "x86_64" ]; then
+  OO_DISTRO=GNOMESlackBuild64
+else
+  OO_DISTRO=GNOMESlackBuild
+fi;
 
-# Set a perl include path so we don't have to spam the build machine
-while read pf; do
-  PERL5LIB=${PERL5LIB:+$PERL5LIB:}$pf
-done << EOPERL5LIB 
-$PKG/usr/$LIBDIR/perl5
-$PKG/usr/$LIBDIR/perl5/site_perl
-$PKG/usr/$LIBDIR/perl5/site_perl/$PERL_VERSION/$PERL_ARCH
-EOPERL5LIB
-export PERL5LIB
+## Configure.
+CFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" CXXFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" \
+  ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var/lib \
+  --mandir=/usr/man $CONFIGURE_FLAGS --target=$ARCH-$DISTRO-linux \
+  --with-distro=$OO_DISTRO \
+  --disable-static --enable-shared \
+  --disable-odk \
+  --enable-access \
+  --enable-cairo \
+  --with-system-cairo \
+  --with-system-sndfile \
+  --with-system-neon \
+  --enable-gtk \
+  --disable-kde \
+  --disable-mono \
+  --disable-pam \
+  --disable-pam-link \
+  --disable-post-install-scripts \
+  --enable-openxml \
+  --with-system-libsvg \
+  --with-binsuffix=3.0 \
+  --with-docdir=/usr/share/doc/openoffice.org \
+  --with-gcc-speedup=ccache \
+  --with-openclipart=/usr/share/openclipart \
+  --with-drink=ale \
+  || exit 1
 
-for MODULE in $MODULE_LIST; 
-do
+## Copy over downloaded sources
+for i in $CWD/{ooo300*,lib*,biblio*,extras*,mdbtools*,scsolver*} ;
+do 
+	echo "Copying to source tree: $i"
+	cp $i ./src 
+done;
+echo
 
-## Decompress archive.
-cd $TMP/$PKGNAME &&
-rm -fr $MODULE && 
-tar xzf $CWD/$MODULE.tar.gz &&
-cd $MODULE || exit 1
+## Build and Install
+make $MAKE_FLAGS -j1 || exit 1
+cd bin ; 
+OODESTDIR=$PKG ./package-ooo || exit 1
 
-perl Makefile.PL || exit 1
+# Add /usr/share/pixmaps directory and link icons to it
+mkdir -p $PKG/usr/pixmaps
+( cd $PKG/usr/pixmaps
+  for APP in base calc draw impress math writer ; do
+    ln -sf /usr/share/icons/hicolor/48x48/apps/ooo-${APP}3.0.png . ;
+  done
+)
 
-## Fix for manpages
-sed -i "s:/share/man:/man:g" Makefile || exit 1
-
-## Build
-make OPTIMIZE="$TUNE_CFLAGS $EXTRA_CFLAGS" CXXFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" $MAKE_FLAGS &&
-make DESTDIR=$PKG install || exit 1
-
+# Make sure our icons specify that we're using 3.0 (and not 2.4)
+# since both can exist on the same system at once
+for i in $PKG/usr/share/applications/*.desktop ;
+do 
+   sed -i '/^Name/s/$/ 3.0/g' $i; 
 done;
 
-# Remove perlocal.pod and .packlist from $PKG
-( for i in perllocal.pod .packlist; do
-      find $PKG -name "$i" -exec rm -rf {} \;
-  done
-) || exit 1
-
-# Remove empty directories
-find $PKG/usr -depth -type d -empty -exec rm -rf {} \;
+# Preserve files
+mv $PKG/etc/bash_completion.d/ooffice3.0.sh $PKG/etc/bash_completion.d/ooffice3.0.sh.new
 
 ## Strip debugging symbols.
 { find $PKG | xargs file | egrep "executable|shared object" | grep "ELF" | \
   cut -d: -f1 | xargs strip --strip-unneeded ; } 2>/dev/null
 
+## Copy extra documentation into package.
+mkdir -p $PKG/usr/doc/$PKGNAME-$VERSION
+for i in README README.html LICENSE LICENSE.html THIRDPARTYLICENSEREADME.html ; do
+  mv -f $PKG/usr/$LIBDIR/ooo-3.0/$i $PKG/usr/doc/$PKGNAME-$VERSION ;
+done
+find $PKG/usr/doc/$PKGNAME-$VERSION/ -type f -exec chmod 644 {} \;
+chown -R root:root $PKG/usr/doc/$PKGNAME-$VERSION
+
 ## Compress and fix manpage links.
-[ -e $PKG/usr/share/man ] && {
-  find $PKG/usr/share/man -type f -name \*.? -exec gzip -9f {} \;
-  find $PKG/usr/share/man -type l -name \*.? -printf \
+[ -e $PKG/usr/man ] && {
+  find $PKG/usr/man -type f -name \*.? -exec gzip -9f {} \;
+  find $PKG/usr/man -type l -name \*.? -printf \
     "( cd '%h'; [ -e '%l.gz' ] &&
      { rm -f '%f'; ln -sf '%l.gz' '%f.gz'; } );\n" | bash
-}
-
-## Deal with .info files.
-[ -e $PKG/usr/info ] && {
-  rm -f $PKG/usr/info/dir
-  gzip -9 $PKG/usr/info/*.info
 }
 
 ## Package meta files
@@ -215,9 +258,9 @@ done
 
 ## Create the package
 cd $PKG
-makepkg -p -l y -c n $PKGDEST/$PKGNAME-${VERSION//-/_}-$ARCH-$BUILD.tgz
+makepkg -p -l y -c n $PKGDEST/$PKGNAME-${VERSION//-/_}-$ARCH-$BUILD.tgz || exit 1
 
 ## Cleanup
 [ "$NOCLEANUP" = "0" ] && {
-  rm -rf $PKG $TMP/$PKGNAME-$VERSION
+  rm -rf $PKG $TMP/ooo-build-$VERSION
 }
