Few minor updates to the SlackBuilds.
I'm 50% through libraries/ - should have the rest done tonight.

diff --git a/src/libraries/gtkunique/gtkunique.SlackBuild b/src/libraries/gtkunique/gtkunique.SlackBuild
--- a/src/libraries/gtkunique/gtkunique.SlackBuild
+++ b/src/libraries/gtkunique/gtkunique.SlackBuild
@@ -6,29 +6,6 @@
 ## Licenced under the terms of the GNU General Public Licence version 3.
 ##
 
-##
-## SVN Warning
-##
-
-cat << EOF
-
-*****************
-* Update Notice *
-*****************
-
-gtkunique is built from an svn repository.  There are no released tarballs.
-If you would like the latest code for this package, please make sure to
-run "svn update" before compiling.  This build script will not update
-the repository automatically (in case specific revisions are wanted.)
-
-***** Note ************
-
-This script is intended to be run from a working svn copy.
-
-***********************
-
-EOF
-
 ## Package variables.
 BUILD=1
 
@@ -49,15 +26,6 @@ PKG=$TMP/package-$PKGNAME
 CWD=$(pwd)
 NOCLEANUP=0
 FORCEBUILD=0
-SVN_REV=$(cd $PKGNAME && svn info 2> /dev/null | grep Revision | cut -d' ' -f2)
-
-if [ "$SVN_REV" = "" ]; then
-  echo "Unable to properly check svn version. Please check your svn setup and try again."
-  exit 1;
-fi;
-
-echo "Building SVN_REV $SVN_REV"
-VERSION=${VERSION:-svn_$SVN_REV}
 
 ## Usage.
 function usage() {
@@ -112,6 +80,29 @@ done
   done
 }
 
+## SVN Warning
+cat << EOF
+***********************************************************
+*** Warning:
+*** This package is built from an svn repository - there
+*** are no released tarballs.  If you would like the latest
+*** code for this package, please make sure to run
+*** "svn update" before compiling.  This build script will
+*** not automatically update the repository (in case
+*** specific revisions are required).
+***
+*** This script must be run from a working svn copy.
+***********************************************************
+EOF
+
+SVN_REV=$(cd $PKGNAME && svn info 2>/dev/null | grep Revision | cut -d' ' -f2)
+[ "$SVN_REV" = "" ] && {
+  echo "Could not get svn revision information.  Check svn sources and try again."
+  exit 1
+}
+
+VERSION="svn_$SVN_REV"
+
 ## Temporary space and package storage.
 mkdir -p $TMP
 rm -rf $PKG
@@ -120,9 +111,9 @@ mkdir -p $PKG/install
 mkdir -p $PKGDEST
 
 ## Copy SVN working copy to temporary space
-rm -fr $TMP/$PKGNAME-$VERSION ;
 cd $TMP &&
-cp -ra $CWD/$PKGNAME ./$PKGNAME-$VERSION &&
+rm -rf $PKGNAME-$VERSION &&
+cp -ra $CWD/$PKGNAME $PKGNAME-$VERSION &&
 cd $PKGNAME-$VERSION || exit 1
 
 # Apply ARCH specific patches.
@@ -187,7 +178,6 @@ EXTRA_CFLAGS=${GSB_EXTRA_CFLAGS:-""}
 MAKE_FLAGS=${GSB_MAKE_FLAGS:-""}
 
 ## Configure.
-
 CFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" CXXFLAGS="$TUNE_CFLAGS $EXTRA_CFLAGS" \
   ./autogen.sh --prefix=/usr --sysconfdir=/etc --localstatedir=/var/lib \
   $CONFIGURE_FLAGS --target=$ARCH-$DISTRO-linux \
